leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
call compileFinal preprocessFileLineNumbers "FAR_revive\FAR_revive_init.sqf";
leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction; //line generated by LEA.
enableSaving [false, false];
[] execVM "VCOMAI\init.sqf";
player setVariable ["FiredTime", 0];
player setVariable ["PLAYERCOMMANDER", 1];
player addEventHandler ["Fired",{null = [_this] spawn FiredAtTarget;}];