/**
* Generated by LEA for Arma 3
* Version: 2.0.18
* Thu Jun 19 22:27:32 CEST 2014
* Mission file name: [FS]CO8_Catch_Papa_Bravo.Altis
* Mission name: [FS]CO8_Catch_Papa_Bravo.Altis
* Required mods:
* + XMedSys
* + ArmA 3
* + TFAR
* + Russians
* 
* Call the script: _dummy = [] execvm "lea\loadoutSingleplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "sql1") then {
removeallweapons sql1;
removeallassigneditems sql1;
removeHeadgear sql1;
removeUniform sql1;
removeBackpack sql1;
removeVest sql1;
removeGoggles sql1;

sql1 addWeapon "ItemMap";
sql1 addWeapon "ItemWatch";
sql1 addWeapon "ItemCompass";
sql1 addWeapon "ItemGPS";
sql1 addWeapon "H_BandMask_demon";
sql1 addWeapon "Binocular";
sql1 addBackpack "B_TacticalPack_blk";
(backpackContainer sql1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
sql1 addWeapon "arifle_MXC_F";
removeBackpack sql1;
sql1 addPrimaryWeaponItem "optic_Aco";
sql1 addBackpack "B_TacticalPack_blk";
(backpackContainer sql1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
sql1 addWeapon "hgun_P07_F";
removeBackpack sql1;
sql1 addBackpack "B_AssaultPack_sgg";
clearItemCargoGlobal (backpackContainer sql1);
clearMagazineCargoGlobal (backpackContainer sql1);
clearWeaponCargoGlobal (backpackContainer sql1);
(backpackContainer sql1) additemcargoGlobal ["x39_bandage",5];
(backpackContainer sql1) additemcargoGlobal ["x39_morphine",5];
(backpackContainer sql1) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer sql1) additemcargoGlobal ["x39_tourniquet",3];
(backpackContainer sql1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",7];
sql1 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer sql1);
clearMagazineCargoGlobal (vestContainer sql1);
clearWeaponCargoGlobal (vestContainer sql1);
(vestContainer sql1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer sql1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
sql1 addItemToVest "SmokeShellGreen";
sql1 addItemToVest "SmokeShellYellow";
sql1 addItemToVest "SmokeShell";
sql1 addItemToVest "HandGrenade";
sql1 addItemToVest "HandGrenade";
sql1 addItemToVest "SmokeShellBlue";
sql1 addItemToVest "SmokeShellRed";
sql1 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer sql1);
clearMagazineCargoGlobal (uniformContainer sql1);
clearWeaponCargoGlobal (uniformContainer sql1);
(uniformContainer sql1) additemcargoGlobal ["x39_earplug",1];
(uniformContainer sql1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",2];
(uniformContainer sql1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
sql1 addWeapon "tf_anprc152";
sql1 selectWeapon (primaryWeapon sql1);
};

if (!isNil "m1") then {
removeallweapons m1;
removeallassigneditems m1;
removeHeadgear m1;
removeUniform m1;
removeBackpack m1;
removeVest m1;
removeGoggles m1;

m1 addWeapon "ItemMap";
m1 addWeapon "ItemWatch";
m1 addWeapon "ItemCompass";
m1 addWeapon "ItemGPS";
m1 addWeapon "H_HelmetB_camo";
m1 addWeapon "Binocular";
m1 addBackpack "B_TacticalPack_blk";
(backpackContainer m1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
m1 addWeapon "arifle_MXC_F";
removeBackpack m1;
m1 addPrimaryWeaponItem "optic_Aco";
m1 addBackpack "B_TacticalPack_blk";
(backpackContainer m1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
m1 addWeapon "hgun_P07_F";
removeBackpack m1;
m1 addBackpack "X39_MedicBackPack";
clearItemCargoGlobal (backpackContainer m1);
clearMagazineCargoGlobal (backpackContainer m1);
clearWeaponCargoGlobal (backpackContainer m1);
(backpackContainer m1) additemcargoGlobal ["x39_medikit",5];
(backpackContainer m1) additemcargoGlobal ["x39_defibrillator",1];
(backpackContainer m1) additemcargoGlobal ["x39_bloodbag",3];
(backpackContainer m1) additemcargoGlobal ["x39_tourniquet",5];
m1 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer m1);
clearMagazineCargoGlobal (vestContainer m1);
clearWeaponCargoGlobal (vestContainer m1);
(vestContainer m1) additemcargoGlobal ["x39_bandage",15];
(vestContainer m1) additemcargoGlobal ["x39_morphine",14];
(vestContainer m1) additemcargoGlobal ["x39_epinephrine",14];
(vestContainer m1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
m1 addItemToVest "SmokeShellGreen";
m1 addItemToVest "SmokeShell";
m1 addItemToVest "SmokeShellRed";
m1 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer m1);
clearMagazineCargoGlobal (uniformContainer m1);
clearWeaponCargoGlobal (uniformContainer m1);
(uniformContainer m1) additemcargoGlobal ["x39_earplug",1];
(uniformContainer m1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(uniformContainer m1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
m1 addWeapon "tf_anprc152";
m1 selectWeapon (primaryWeapon m1);
};

if (!isNil "tl1") then {
removeallweapons tl1;
removeallassigneditems tl1;
removeHeadgear tl1;
removeUniform tl1;
removeBackpack tl1;
removeVest tl1;
removeGoggles tl1;

tl1 addWeapon "ItemMap";
tl1 addWeapon "ItemWatch";
tl1 addWeapon "ItemCompass";
tl1 addWeapon "ItemGPS";
tl1 addWeapon "H_BandMask_demon";
tl1 addWeapon "Binocular";
tl1 addBackpack "B_TacticalPack_blk";
(backpackContainer tl1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
tl1 addWeapon "arifle_MXC_F";
removeBackpack tl1;
tl1 addPrimaryWeaponItem "optic_Aco";
tl1 addBackpack "B_TacticalPack_blk";
(backpackContainer tl1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
tl1 addWeapon "hgun_P07_F";
removeBackpack tl1;
tl1 addBackpack "B_AssaultPack_sgg";
clearItemCargoGlobal (backpackContainer tl1);
clearMagazineCargoGlobal (backpackContainer tl1);
clearWeaponCargoGlobal (backpackContainer tl1);
(backpackContainer tl1) additemcargoGlobal ["x39_bandage",5];
(backpackContainer tl1) additemcargoGlobal ["x39_morphine",5];
(backpackContainer tl1) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer tl1) additemcargoGlobal ["x39_tourniquet",3];
(backpackContainer tl1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",7];
tl1 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer tl1);
clearMagazineCargoGlobal (vestContainer tl1);
clearWeaponCargoGlobal (vestContainer tl1);
(vestContainer tl1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer tl1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
tl1 addItemToVest "SmokeShellGreen";
tl1 addItemToVest "SmokeShellYellow";
tl1 addItemToVest "SmokeShell";
tl1 addItemToVest "HandGrenade";
tl1 addItemToVest "HandGrenade";
tl1 addItemToVest "SmokeShellBlue";
tl1 addItemToVest "SmokeShellRed";
tl1 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer tl1);
clearMagazineCargoGlobal (uniformContainer tl1);
clearWeaponCargoGlobal (uniformContainer tl1);
(uniformContainer tl1) additemcargoGlobal ["x39_earplug",1];
(uniformContainer tl1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",2];
(uniformContainer tl1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
tl1 addWeapon "tf_anprc152";
tl1 selectWeapon (primaryWeapon tl1);
};

if (!isNil "s1") then {
removeallweapons s1;
removeallassigneditems s1;
removeHeadgear s1;
removeUniform s1;
removeBackpack s1;
removeVest s1;
removeGoggles s1;

s1 addWeapon "ItemMap";
s1 addWeapon "ItemWatch";
s1 addWeapon "ItemCompass";
s1 addWeapon "ItemGPS";
s1 addWeapon "H_HelmetB_camo";
s1 addWeapon "Binocular";
s1 addBackpack "B_TacticalPack_blk";
(backpackContainer s1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
s1 addWeapon "arifle_MXC_F";
removeBackpack s1;
s1 addPrimaryWeaponItem "optic_Aco";
s1 addBackpack "B_TacticalPack_blk";
(backpackContainer s1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
s1 addWeapon "hgun_P07_F";
removeBackpack s1;
s1 addBackpack "B_TacticalPack_oli";
clearItemCargoGlobal (backpackContainer s1);
clearMagazineCargoGlobal (backpackContainer s1);
clearWeaponCargoGlobal (backpackContainer s1);
(backpackContainer s1) additemcargoGlobal ["x39_bandage",5];
(backpackContainer s1) additemcargoGlobal ["x39_morphine",5];
(backpackContainer s1) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer s1) additemcargoGlobal ["x39_tourniquet",2];
(backpackContainer s1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(backpackContainer s1) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",4];
s1 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer s1);
clearMagazineCargoGlobal (vestContainer s1);
clearWeaponCargoGlobal (vestContainer s1);
(vestContainer s1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",7];
(vestContainer s1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
s1 addItemToVest "SmokeShellGreen";
s1 addItemToVest "SmokeShellYellow";
s1 addItemToVest "SmokeShell";
s1 addItemToVest "HandGrenade";
s1 addItemToVest "HandGrenade";
s1 addItemToVest "SmokeShellBlue";
s1 addItemToVest "SmokeShellRed";
s1 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer s1);
clearMagazineCargoGlobal (uniformContainer s1);
clearWeaponCargoGlobal (uniformContainer s1);
(uniformContainer s1) additemcargoGlobal ["x39_earplug",1];
(uniformContainer s1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(uniformContainer s1) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
s1 addWeapon "tf_anprc152";
s1 selectWeapon (primaryWeapon s1);
};

if (!isNil "m2") then {
removeallweapons m2;
removeallassigneditems m2;
removeHeadgear m2;
removeUniform m2;
removeBackpack m2;
removeVest m2;
removeGoggles m2;

m2 addWeapon "ItemMap";
m2 addWeapon "ItemWatch";
m2 addWeapon "ItemCompass";
m2 addWeapon "ItemGPS";
m2 addWeapon "H_HelmetB_camo";
m2 addWeapon "Binocular";
m2 addBackpack "B_TacticalPack_blk";
(backpackContainer m2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
m2 addWeapon "arifle_MXC_F";
removeBackpack m2;
m2 addPrimaryWeaponItem "optic_Aco";
m2 addBackpack "B_TacticalPack_blk";
(backpackContainer m2) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
m2 addWeapon "hgun_P07_F";
removeBackpack m2;
m2 addBackpack "X39_MedicBackPack";
clearItemCargoGlobal (backpackContainer m2);
clearMagazineCargoGlobal (backpackContainer m2);
clearWeaponCargoGlobal (backpackContainer m2);
(backpackContainer m2) additemcargoGlobal ["x39_medikit",5];
(backpackContainer m2) additemcargoGlobal ["x39_defibrillator",1];
(backpackContainer m2) additemcargoGlobal ["x39_bloodbag",3];
(backpackContainer m2) additemcargoGlobal ["x39_tourniquet",5];
m2 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer m2);
clearMagazineCargoGlobal (vestContainer m2);
clearWeaponCargoGlobal (vestContainer m2);
(vestContainer m2) additemcargoGlobal ["x39_bandage",15];
(vestContainer m2) additemcargoGlobal ["x39_morphine",14];
(vestContainer m2) additemcargoGlobal ["x39_epinephrine",14];
(vestContainer m2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
m2 addItemToVest "SmokeShellGreen";
m2 addItemToVest "SmokeShell";
m2 addItemToVest "SmokeShellRed";
m2 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer m2);
clearMagazineCargoGlobal (uniformContainer m2);
clearWeaponCargoGlobal (uniformContainer m2);
(uniformContainer m2) additemcargoGlobal ["x39_earplug",1];
(uniformContainer m2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(uniformContainer m2) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
m2 addWeapon "tf_anprc152";
m2 selectWeapon (primaryWeapon m2);
};

if (!isNil "s2") then {
removeallweapons s2;
removeallassigneditems s2;
removeHeadgear s2;
removeUniform s2;
removeBackpack s2;
removeVest s2;
removeGoggles s2;

s2 addWeapon "ItemMap";
s2 addWeapon "ItemWatch";
s2 addWeapon "ItemCompass";
s2 addWeapon "ItemGPS";
s2 addWeapon "H_HelmetB_camo";
s2 addWeapon "Binocular";
s2 addBackpack "B_TacticalPack_blk";
(backpackContainer s2) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
s2 addWeapon "LMG_Mk200_F";
removeBackpack s2;
s2 addPrimaryWeaponItem "optic_Aco";
s2 addBackpack "B_TacticalPack_blk";
(backpackContainer s2) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
s2 addWeapon "hgun_P07_F";
removeBackpack s2;
s2 addBackpack "B_AssaultPack_sgg";
clearItemCargoGlobal (backpackContainer s2);
clearMagazineCargoGlobal (backpackContainer s2);
clearWeaponCargoGlobal (backpackContainer s2);
(backpackContainer s2) additemcargoGlobal ["x39_bandage",5];
(backpackContainer s2) additemcargoGlobal ["x39_morphine",5];
(backpackContainer s2) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer s2) additemcargoGlobal ["x39_tourniquet",3];
(backpackContainer s2) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",2];
s2 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer s2);
clearMagazineCargoGlobal (vestContainer s2);
clearWeaponCargoGlobal (vestContainer s2);
(vestContainer s2) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
(vestContainer s2) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
s2 addItemToVest "SmokeShellGreen";
s2 addItemToVest "SmokeShellYellow";
s2 addItemToVest "SmokeShell";
s2 addItemToVest "HandGrenade";
s2 addItemToVest "HandGrenade";
s2 addItemToVest "SmokeShellBlue";
s2 addItemToVest "SmokeShellRed";
s2 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer s2);
clearMagazineCargoGlobal (uniformContainer s2);
clearWeaponCargoGlobal (uniformContainer s2);
(uniformContainer s2) additemcargoGlobal ["x39_earplug",1];
(uniformContainer s2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",2];
(uniformContainer s2) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
s2 addWeapon "tf_anprc152";
s2 selectWeapon (primaryWeapon s2);
};

if (!isNil "s3") then {
removeallweapons s3;
removeallassigneditems s3;
removeHeadgear s3;
removeUniform s3;
removeBackpack s3;
removeVest s3;
removeGoggles s3;

s3 addWeapon "ItemMap";
s3 addWeapon "ItemWatch";
s3 addWeapon "ItemCompass";
s3 addWeapon "ItemGPS";
s3 addWeapon "H_HelmetB_camo";
s3 addWeapon "Binocular";
s3 addBackpack "B_TacticalPack_blk";
(backpackContainer s3) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
s3 addWeapon "arifle_MXC_F";
removeBackpack s3;
s3 addPrimaryWeaponItem "optic_Aco";
s3 addBackpack "B_TacticalPack_blk";
(backpackContainer s3) addmagazinecargoGlobal ["NLAW_F",1];
s3 addWeapon "launch_NLAW_F";
removeBackpack s3;
s3 addBackpack "B_TacticalPack_blk";
(backpackContainer s3) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
s3 addWeapon "hgun_P07_F";
removeBackpack s3;
s3 addBackpack "B_Bergen_blk";
clearItemCargoGlobal (backpackContainer s3);
clearMagazineCargoGlobal (backpackContainer s3);
clearWeaponCargoGlobal (backpackContainer s3);
(backpackContainer s3) additemcargoGlobal ["x39_bandage",5];
(backpackContainer s3) additemcargoGlobal ["x39_morphine",5];
(backpackContainer s3) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer s3) additemcargoGlobal ["x39_tourniquet",1];
(backpackContainer s3) addmagazinecargoGlobal ["NLAW_F",3];
s3 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer s3);
clearMagazineCargoGlobal (vestContainer s3);
clearWeaponCargoGlobal (vestContainer s3);
(vestContainer s3) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",9];
(vestContainer s3) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
s3 addItemToVest "SmokeShellGreen";
s3 addItemToVest "SmokeShellYellow";
s3 addItemToVest "SmokeShell";
s3 addItemToVest "HandGrenade";
s3 addItemToVest "HandGrenade";
s3 addItemToVest "SmokeShellBlue";
s3 addItemToVest "SmokeShellRed";
s3 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer s3);
clearMagazineCargoGlobal (uniformContainer s3);
clearWeaponCargoGlobal (uniformContainer s3);
(uniformContainer s3) additemcargoGlobal ["x39_earplug",1];
(uniformContainer s3) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(uniformContainer s3) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
s3 addWeapon "tf_anprc152";
s3 selectWeapon (primaryWeapon s3);
};

if (!isNil "s4") then {
removeallweapons s4;
removeallassigneditems s4;
removeHeadgear s4;
removeUniform s4;
removeBackpack s4;
removeVest s4;
removeGoggles s4;

s4 addWeapon "ItemMap";
s4 addWeapon "ItemWatch";
s4 addWeapon "ItemCompass";
s4 addWeapon "ItemGPS";
s4 addWeapon "H_HelmetB_camo";
s4 addWeapon "Binocular";
s4 addBackpack "B_TacticalPack_blk";
(backpackContainer s4) addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",1];
s4 addWeapon "arifle_MX_GL_F";
removeBackpack s4;
s4 addPrimaryWeaponItem "optic_Aco";
s4 addBackpack "B_TacticalPack_blk";
(backpackContainer s4) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
s4 addWeapon "hgun_P07_F";
removeBackpack s4;
s4 addBackpack "B_AssaultPack_sgg";
clearItemCargoGlobal (backpackContainer s4);
clearMagazineCargoGlobal (backpackContainer s4);
clearWeaponCargoGlobal (backpackContainer s4);
(backpackContainer s4) additemcargoGlobal ["x39_bandage",5];
(backpackContainer s4) additemcargoGlobal ["x39_morphine",5];
(backpackContainer s4) additemcargoGlobal ["x39_epinephrine",5];
(backpackContainer s4) additemcargoGlobal ["x39_tourniquet",3];
(backpackContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",1];
(backpackContainer s4) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",7];
(backpackContainer s4) addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",1];
(backpackContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",1];
(backpackContainer s4) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",10];
s4 addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer s4);
clearMagazineCargoGlobal (vestContainer s4);
clearWeaponCargoGlobal (vestContainer s4);
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeOrange_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer s4) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",1];
(vestContainer s4) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
s4 addItemToVest "HandGrenade";
s4 addUniform "U_B_CombatUniform_mcam_vest";
clearItemCargoGlobal (uniformContainer s4);
clearMagazineCargoGlobal (uniformContainer s4);
clearWeaponCargoGlobal (uniformContainer s4);
(uniformContainer s4) additemcargoGlobal ["x39_earplug",1];
(uniformContainer s4) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",3];
(uniformContainer s4) addmagazinecargoGlobal ["16Rnd_9x21_Mag",2];
s4 addWeapon "tf_anprc152";
s4 selectWeapon (primaryWeapon s4);
};

if (!isNil "Anton") then {
removeallweapons Anton;
removeallassigneditems Anton;
removeHeadgear Anton;
removeUniform Anton;
removeBackpack Anton;
removeVest Anton;
removeGoggles Anton;

Anton addWeapon "G_Shades_Black";
Anton addBackpack "B_TacticalPack_blk";
(backpackContainer Anton) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",1];
Anton addWeapon "hgun_Pistol_heavy_02_F";
removeBackpack Anton;
Anton addHandgunItem "optic_Yorris";
Anton addBackpack "RU_AssaultPack";
clearItemCargoGlobal (backpackContainer Anton);
clearMagazineCargoGlobal (backpackContainer Anton);
clearWeaponCargoGlobal (backpackContainer Anton);
(backpackContainer Anton) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",3];
Anton addUniform "U_RU_Pilot_Suit";
clearItemCargoGlobal (uniformContainer Anton);
clearMagazineCargoGlobal (uniformContainer Anton);
clearWeaponCargoGlobal (uniformContainer Anton);
if (count weapons Anton > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Anton) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Anton selectWeapon (_muzzles select 0);
  }
  else {
     Anton selectWeapon _type;
  };
};
};

