leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

call compileFinal preprocessFileLineNumbers "FAR_revive\FAR_revive_init.sqf";
enableSaving [false, false];
