leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.


//itemspawn
if (isServer) then {call compile preprocessFile "scripts\locationlist.sqf";};

_side = createCenter east;

//hide markers for UPS script
"pat1" setMarkerPos [-(getMarkerPos "pat1" select 0),-(getMarkerPos "pat1" select 1)];
"pat2" setMarkerPos [-(getMarkerPos "pat2" select 0),-(getMarkerPos "pat2" select 1)];
"pat3" setMarkerPos [-(getMarkerPos "pat3" select 0),-(getMarkerPos "pat3" select 1)];
"pat4" setMarkerPos [-(getMarkerPos "pat4" select 0),-(getMarkerPos "pat4" select 1)];
{_x setMarkerAlphaLocal 0} foreach ["pat1","pat2","pat3","pat4"];

//create Trigger for northern mission part
private ["_patTrigger"];
_patTrigger = ["patTriggerObj0",1700,1,0,true,west,"PRESENT",false] call ATR_fnc_createTrigger;
_patTrigger setTriggerStatements ["this","[] call ATR_fnc_patsNorth",""]; 

//add obj2 topic to all player units
private ["_players"];
_players = [tl1,gl2,player1,player2];
{
     _x kbaddTopic ["costia", "kb\costia.bikb", "", compile preprocessFileLineNumbers "kb\player.sqf"];
} forEach [tl1,gl2,player1,player2];

//assign name to informant
costia setidentity "costiaPapadopolous";