/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Fri May 16 11:52:55 CEST 2014
* Mission file name: [FS]co8_Make_love_not_war.Altis
* Mission name: [FS]co8_Make_love_not_war.Altis
* Required mods:
* + ArmA 3
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/


/**
* Loadout for soldiers units
*/

if (player == Squadleader) exitwith {
removeallweapons Squadleader;
removeallassigneditems Squadleader;
removeHeadgear Squadleader;
removeBackpack Squadleader;
removeVest Squadleader;

Squadleader addWeapon "ItemMap";
Squadleader addWeapon "ItemWatch";
Squadleader addWeapon "ItemCompass";
Squadleader addWeapon "ItemGPS";
Squadleader addWeapon "H_Bandanna_camo";
Squadleader addWeapon "NVGoggles";
Squadleader addWeapon "Rangefinder";
Squadleader addBackpack "B_TacticalPack_blk";
(backpackContainer Squadleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Squadleader addWeapon "arifle_MX_F";
removeBackpack Squadleader;
Squadleader addPrimaryWeaponItem "acc_pointer_IR";
Squadleader addPrimaryWeaponItem "muzzle_snds_H";
Squadleader addPrimaryWeaponItem "optic_Aco";
Squadleader addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Squadleader);
clearMagazineCargoGlobal (backpackContainer Squadleader);
clearWeaponCargoGlobal (backpackContainer Squadleader);
(backpackContainer Squadleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Squadleader addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Squadleader);
clearMagazineCargoGlobal (vestContainer Squadleader);
clearWeaponCargoGlobal (vestContainer Squadleader);
(vestContainer Squadleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Squadleader);
clearMagazineCargoGlobal (uniformContainer Squadleader);
clearWeaponCargoGlobal (uniformContainer Squadleader);
(uniformContainer Squadleader) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Squadleader) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Squadleader) addmagazinecargoGlobal ["B_IR_Grenade",1];
Squadleader addWeapon "tf_anprc152";
Squadleader selectWeapon (primaryWeapon Squadleader);
};

if (player == Teamleader) exitwith {
removeallweapons Teamleader;
removeallassigneditems Teamleader;
removeHeadgear Teamleader;
removeBackpack Teamleader;
removeVest Teamleader;

Teamleader addWeapon "ItemMap";
Teamleader addWeapon "ItemWatch";
Teamleader addWeapon "ItemCompass";
Teamleader addWeapon "ItemGPS";
Teamleader addWeapon "H_Bandanna_camo";
Teamleader addWeapon "NVGoggles";
Teamleader addWeapon "Rangefinder";
Teamleader addBackpack "B_TacticalPack_blk";
(backpackContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Teamleader addWeapon "arifle_MX_F";
removeBackpack Teamleader;
Teamleader addPrimaryWeaponItem "acc_pointer_IR";
Teamleader addPrimaryWeaponItem "muzzle_snds_H";
Teamleader addPrimaryWeaponItem "optic_Aco";
Teamleader addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Teamleader);
clearMagazineCargoGlobal (backpackContainer Teamleader);
clearWeaponCargoGlobal (backpackContainer Teamleader);
(backpackContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Teamleader addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Teamleader);
clearMagazineCargoGlobal (vestContainer Teamleader);
clearWeaponCargoGlobal (vestContainer Teamleader);
(vestContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Teamleader);
clearMagazineCargoGlobal (uniformContainer Teamleader);
clearWeaponCargoGlobal (uniformContainer Teamleader);
(uniformContainer Teamleader) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Teamleader) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Teamleader) addmagazinecargoGlobal ["B_IR_Grenade",1];
Teamleader addWeapon "tf_anprc152";
Teamleader selectWeapon (primaryWeapon Teamleader);
};

if (player == Schuetze) exitwith {
removeallweapons Schuetze;
removeallassigneditems Schuetze;
removeHeadgear Schuetze;
removeBackpack Schuetze;
removeVest Schuetze;

Schuetze addWeapon "ItemMap";
Schuetze addWeapon "ItemWatch";
Schuetze addWeapon "ItemCompass";
Schuetze addWeapon "ItemGPS";
Schuetze addWeapon "H_Bandanna_camo";
Schuetze addWeapon "NVGoggles";
Schuetze addWeapon "Rangefinder";
Schuetze addBackpack "B_TacticalPack_blk";
(backpackContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Schuetze addWeapon "arifle_MX_F";
removeBackpack Schuetze;
Schuetze addPrimaryWeaponItem "acc_pointer_IR";
Schuetze addPrimaryWeaponItem "muzzle_snds_H";
Schuetze addPrimaryWeaponItem "optic_Aco";
Schuetze addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Schuetze);
clearMagazineCargoGlobal (backpackContainer Schuetze);
clearWeaponCargoGlobal (backpackContainer Schuetze);
(backpackContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Schuetze addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Schuetze);
clearMagazineCargoGlobal (vestContainer Schuetze);
clearWeaponCargoGlobal (vestContainer Schuetze);
(vestContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Schuetze);
clearMagazineCargoGlobal (uniformContainer Schuetze);
clearWeaponCargoGlobal (uniformContainer Schuetze);
(uniformContainer Schuetze) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Schuetze) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Schuetze) addmagazinecargoGlobal ["B_IR_Grenade",1];
Schuetze addWeapon "tf_anprc152";
Schuetze selectWeapon (primaryWeapon Schuetze);
};

if (player == Schuetze2) exitwith {
removeallweapons Schuetze2;
removeallassigneditems Schuetze2;
removeHeadgear Schuetze2;
removeBackpack Schuetze2;
removeVest Schuetze2;

Schuetze2 addWeapon "ItemMap";
Schuetze2 addWeapon "ItemWatch";
Schuetze2 addWeapon "ItemCompass";
Schuetze2 addWeapon "ItemGPS";
Schuetze2 addWeapon "H_Bandanna_camo";
Schuetze2 addWeapon "NVGoggles";
Schuetze2 addWeapon "Rangefinder";
Schuetze2 addBackpack "B_TacticalPack_blk";
(backpackContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Schuetze2 addWeapon "arifle_MX_F";
removeBackpack Schuetze2;
Schuetze2 addPrimaryWeaponItem "acc_pointer_IR";
Schuetze2 addPrimaryWeaponItem "muzzle_snds_H";
Schuetze2 addPrimaryWeaponItem "optic_Aco";
Schuetze2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Schuetze2);
clearMagazineCargoGlobal (backpackContainer Schuetze2);
clearWeaponCargoGlobal (backpackContainer Schuetze2);
(backpackContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Schuetze2 addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Schuetze2);
clearMagazineCargoGlobal (vestContainer Schuetze2);
clearWeaponCargoGlobal (vestContainer Schuetze2);
(vestContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Schuetze2);
clearMagazineCargoGlobal (uniformContainer Schuetze2);
clearWeaponCargoGlobal (uniformContainer Schuetze2);
(uniformContainer Schuetze2) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Schuetze2) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Schuetze2) addmagazinecargoGlobal ["B_IR_Grenade",1];
Schuetze2 addWeapon "tf_anprc152";
Schuetze2 selectWeapon (primaryWeapon Schuetze2);
};

if (player == Marksman) exitwith {
removeallweapons Marksman;
removeallassigneditems Marksman;
removeHeadgear Marksman;
removeBackpack Marksman;
removeVest Marksman;

Marksman addWeapon "ItemMap";
Marksman addWeapon "ItemWatch";
Marksman addWeapon "ItemCompass";
Marksman addWeapon "ItemGPS";
Marksman addWeapon "H_Bandanna_camo";
Marksman addWeapon "NVGoggles";
Marksman addWeapon "Rangefinder";
Marksman addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
Marksman addWeapon "srifle_EBR_F";
removeBackpack Marksman;
Marksman addPrimaryWeaponItem "muzzle_snds_B";
Marksman addPrimaryWeaponItem "optic_NVS";
Marksman addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Marksman);
clearMagazineCargoGlobal (backpackContainer Marksman);
clearWeaponCargoGlobal (backpackContainer Marksman);
(backpackContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",20];
Marksman addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Marksman);
clearMagazineCargoGlobal (vestContainer Marksman);
clearWeaponCargoGlobal (vestContainer Marksman);
(vestContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",14];
clearItemCargoGlobal (uniformContainer Marksman);
clearMagazineCargoGlobal (uniformContainer Marksman);
clearWeaponCargoGlobal (uniformContainer Marksman);
(uniformContainer Marksman) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Marksman) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Marksman) addmagazinecargoGlobal ["B_IR_Grenade",1];
Marksman addWeapon "tf_anprc152";
Marksman selectWeapon (primaryWeapon Marksman);
};

if (player == Sprengmeister) exitwith {
removeallweapons Sprengmeister;
removeallassigneditems Sprengmeister;
removeHeadgear Sprengmeister;
removeBackpack Sprengmeister;
removeVest Sprengmeister;

Sprengmeister addWeapon "ItemMap";
Sprengmeister addWeapon "ItemWatch";
Sprengmeister addWeapon "ItemCompass";
Sprengmeister addWeapon "ItemGPS";
Sprengmeister addWeapon "H_Bandanna_camo";
Sprengmeister addWeapon "NVGoggles";
Sprengmeister addWeapon "Rangefinder";
Sprengmeister addBackpack "B_TacticalPack_blk";
(backpackContainer Sprengmeister) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Sprengmeister addWeapon "arifle_MX_F";
removeBackpack Sprengmeister;
Sprengmeister addPrimaryWeaponItem "acc_pointer_IR";
Sprengmeister addPrimaryWeaponItem "muzzle_snds_H";
Sprengmeister addPrimaryWeaponItem "optic_Aco";
Sprengmeister addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Sprengmeister);
clearMagazineCargoGlobal (backpackContainer Sprengmeister);
clearWeaponCargoGlobal (backpackContainer Sprengmeister);
(backpackContainer Sprengmeister) addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
(backpackContainer Sprengmeister) addmagazinecargoGlobal ["DemoCharge_Remote_Mag",3];
Sprengmeister addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Sprengmeister);
clearMagazineCargoGlobal (vestContainer Sprengmeister);
clearWeaponCargoGlobal (vestContainer Sprengmeister);
(vestContainer Sprengmeister) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Sprengmeister);
clearMagazineCargoGlobal (uniformContainer Sprengmeister);
clearWeaponCargoGlobal (uniformContainer Sprengmeister);
(uniformContainer Sprengmeister) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Sprengmeister) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Sprengmeister) addmagazinecargoGlobal ["B_IR_Grenade",1];
Sprengmeister addWeapon "tf_anprc152";
Sprengmeister selectWeapon (primaryWeapon Sprengmeister);
};

if (player == Marksman2) exitwith {
removeallweapons Marksman2;
removeallassigneditems Marksman2;
removeHeadgear Marksman2;
removeBackpack Marksman2;
removeVest Marksman2;

Marksman2 addWeapon "ItemMap";
Marksman2 addWeapon "ItemWatch";
Marksman2 addWeapon "ItemCompass";
Marksman2 addWeapon "ItemGPS";
Marksman2 addWeapon "H_Bandanna_camo";
Marksman2 addWeapon "NVGoggles";
Marksman2 addWeapon "Rangefinder";
Marksman2 addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
Marksman2 addWeapon "srifle_EBR_F";
removeBackpack Marksman2;
Marksman2 addPrimaryWeaponItem "muzzle_snds_B";
Marksman2 addPrimaryWeaponItem "optic_NVS";
Marksman2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Marksman2);
clearMagazineCargoGlobal (backpackContainer Marksman2);
clearWeaponCargoGlobal (backpackContainer Marksman2);
(backpackContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",20];
Marksman2 addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Marksman2);
clearMagazineCargoGlobal (vestContainer Marksman2);
clearWeaponCargoGlobal (vestContainer Marksman2);
(vestContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",14];
clearItemCargoGlobal (uniformContainer Marksman2);
clearMagazineCargoGlobal (uniformContainer Marksman2);
clearWeaponCargoGlobal (uniformContainer Marksman2);
(uniformContainer Marksman2) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Marksman2) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Marksman2) addmagazinecargoGlobal ["B_IR_Grenade",1];
Marksman2 addWeapon "tf_anprc152";
Marksman2 selectWeapon (primaryWeapon Marksman2);
};

if (player == Sprengmeister2) exitwith {
removeallweapons Sprengmeister2;
removeallassigneditems Sprengmeister2;
removeHeadgear Sprengmeister2;
removeBackpack Sprengmeister2;
removeVest Sprengmeister2;

Sprengmeister2 addWeapon "ItemMap";
Sprengmeister2 addWeapon "ItemWatch";
Sprengmeister2 addWeapon "ItemCompass";
Sprengmeister2 addWeapon "ItemGPS";
Sprengmeister2 addWeapon "H_Bandanna_camo";
Sprengmeister2 addWeapon "NVGoggles";
Sprengmeister2 addWeapon "Rangefinder";
Sprengmeister2 addBackpack "B_TacticalPack_blk";
(backpackContainer Sprengmeister2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Sprengmeister2 addWeapon "arifle_MX_F";
removeBackpack Sprengmeister2;
Sprengmeister2 addPrimaryWeaponItem "acc_pointer_IR";
Sprengmeister2 addPrimaryWeaponItem "muzzle_snds_H";
Sprengmeister2 addPrimaryWeaponItem "optic_Aco";
Sprengmeister2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Sprengmeister2);
clearMagazineCargoGlobal (backpackContainer Sprengmeister2);
clearWeaponCargoGlobal (backpackContainer Sprengmeister2);
(backpackContainer Sprengmeister2) addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
(backpackContainer Sprengmeister2) addmagazinecargoGlobal ["DemoCharge_Remote_Mag",3];
Sprengmeister2 addVest "V_PlateCarrier_Kerry";
clearItemCargoGlobal (vestContainer Sprengmeister2);
clearMagazineCargoGlobal (vestContainer Sprengmeister2);
clearWeaponCargoGlobal (vestContainer Sprengmeister2);
(vestContainer Sprengmeister2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Sprengmeister2);
clearMagazineCargoGlobal (uniformContainer Sprengmeister2);
clearWeaponCargoGlobal (uniformContainer Sprengmeister2);
(uniformContainer Sprengmeister2) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer Sprengmeister2) addmagazinecargoGlobal ["SmokeShellRed",3];
(uniformContainer Sprengmeister2) addmagazinecargoGlobal ["B_IR_Grenade",1];
Sprengmeister2 addWeapon "tf_anprc152";
Sprengmeister2 selectWeapon (primaryWeapon Sprengmeister2);
};

