/**
* Generated by LEA for Arma 3
* Version: 2.0.18
* Tue May 27 18:05:51 CEST 2014
* Mission file name: [FS]co8_Make_love_not_war.Altis
* Mission name: [FS]co8_Make_love_not_war.Altis
* Required mods:
* + ArmA 3
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal unit_97_281;
  clearmagazinecargoGlobal unit_97_281;
  clearitemcargoGlobal unit_97_281;

  unit_97_281 addweaponcargoGlobal ["arifle_MX_F",3];
  unit_97_281 addweaponcargoGlobal ["srifle_EBR_F",1];
  unit_97_281 addmagazinecargoGlobal ["20Rnd_762x51_Mag",10];
  unit_97_281 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
  unit_97_281 additemcargoGlobal ["muzzle_snds_B",1];
  unit_97_281 additemcargoGlobal ["optic_NVS",1];
  unit_97_281 additemcargoGlobal ["optic_Aco",3];
  unit_97_281 additemcargoGlobal ["muzzle_snds_H",3];

  clearweaponcargoGlobal unit_97_282;
  clearmagazinecargoGlobal unit_97_282;
  clearitemcargoGlobal unit_97_282;

  unit_97_282 addweaponcargoGlobal ["arifle_MX_F",3];
  unit_97_282 addweaponcargoGlobal ["srifle_EBR_F",1];
  unit_97_282 addmagazinecargoGlobal ["20Rnd_762x51_Mag",10];
  unit_97_282 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
  unit_97_282 additemcargoGlobal ["muzzle_snds_B",1];
  unit_97_282 additemcargoGlobal ["optic_NVS",1];
  unit_97_282 additemcargoGlobal ["optic_Aco",3];
  unit_97_282 additemcargoGlobal ["muzzle_snds_H",3];

  clearweaponcargoGlobal unit_97_283;
  clearmagazinecargoGlobal unit_97_283;
  clearitemcargoGlobal unit_97_283;

  unit_97_283 addweaponcargoGlobal ["arifle_MX_F",3];
  unit_97_283 addweaponcargoGlobal ["srifle_EBR_F",1];
  unit_97_283 addmagazinecargoGlobal ["20Rnd_762x51_Mag",10];
  unit_97_283 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
  unit_97_283 additemcargoGlobal ["muzzle_snds_B",1];
  unit_97_283 additemcargoGlobal ["optic_NVS",1];
  unit_97_283 additemcargoGlobal ["optic_Aco",3];
  unit_97_283 additemcargoGlobal ["muzzle_snds_H",3];


/**
* Loadout for soldiers units
*/

if (!isNil "Squadlead") then {
removeallweapons Squadlead;
removeallassigneditems Squadlead;
removeHeadgear Squadlead;
removeBackpack Squadlead;
removeVest Squadlead;
removeGoggles Squadlead;

Squadlead addWeapon "ItemMap";
Squadlead addWeapon "ItemWatch";
Squadlead addWeapon "ItemCompass";
Squadlead addWeapon "ItemGPS";
Squadlead addWeapon "H_Bandanna_camo";
Squadlead addWeapon "NVGoggles";
Squadlead addWeapon "Rangefinder";
Squadlead addBackpack "B_TacticalPack_blk";
(backpackContainer Squadlead) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Squadlead addWeapon "arifle_MX_F";
removeBackpack Squadlead;
Squadlead addPrimaryWeaponItem "acc_pointer_IR";
Squadlead addPrimaryWeaponItem "muzzle_snds_H";
Squadlead addPrimaryWeaponItem "optic_Aco";
Squadlead addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Squadlead);
clearMagazineCargoGlobal (backpackContainer Squadlead);
clearWeaponCargoGlobal (backpackContainer Squadlead);
(backpackContainer Squadlead) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Squadlead addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Squadlead);
clearMagazineCargoGlobal (vestContainer Squadlead);
clearWeaponCargoGlobal (vestContainer Squadlead);
(vestContainer Squadlead) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Squadlead);
clearMagazineCargoGlobal (uniformContainer Squadlead);
clearWeaponCargoGlobal (uniformContainer Squadlead);
Squadlead addItemToUniform "SmokeShellGreen";
Squadlead addItemToUniform "SmokeShellGreen";
Squadlead addItemToUniform "SmokeShellGreen";
Squadlead addItemToUniform "SmokeShellGreen";
Squadlead addItemToUniform "SmokeShellGreen";
Squadlead addItemToUniform "SmokeShellRed";
Squadlead addItemToUniform "SmokeShellRed";
Squadlead addItemToUniform "SmokeShellRed";
Squadlead addItemToUniform "B_IR_Grenade";
Squadlead addWeapon "tf_anprc152";
Squadlead selectWeapon (primaryWeapon Squadlead);
};

if (!isNil "Teamleader") then {
removeallweapons Teamleader;
removeallassigneditems Teamleader;
removeHeadgear Teamleader;
removeBackpack Teamleader;
removeVest Teamleader;
removeGoggles Teamleader;

Teamleader addWeapon "ItemMap";
Teamleader addWeapon "ItemWatch";
Teamleader addWeapon "ItemCompass";
Teamleader addWeapon "ItemGPS";
Teamleader addWeapon "H_Bandanna_camo";
Teamleader addWeapon "NVGoggles";
Teamleader addWeapon "Rangefinder";
Teamleader addBackpack "B_TacticalPack_blk";
(backpackContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Teamleader addWeapon "arifle_MX_F";
removeBackpack Teamleader;
Teamleader addPrimaryWeaponItem "acc_pointer_IR";
Teamleader addPrimaryWeaponItem "muzzle_snds_H";
Teamleader addPrimaryWeaponItem "optic_Aco";
Teamleader addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Teamleader);
clearMagazineCargoGlobal (backpackContainer Teamleader);
clearWeaponCargoGlobal (backpackContainer Teamleader);
(backpackContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Teamleader addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Teamleader);
clearMagazineCargoGlobal (vestContainer Teamleader);
clearWeaponCargoGlobal (vestContainer Teamleader);
(vestContainer Teamleader) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Teamleader);
clearMagazineCargoGlobal (uniformContainer Teamleader);
clearWeaponCargoGlobal (uniformContainer Teamleader);
Teamleader addItemToUniform "SmokeShellGreen";
Teamleader addItemToUniform "SmokeShellGreen";
Teamleader addItemToUniform "SmokeShellGreen";
Teamleader addItemToUniform "SmokeShellGreen";
Teamleader addItemToUniform "SmokeShellGreen";
Teamleader addItemToUniform "SmokeShellRed";
Teamleader addItemToUniform "SmokeShellRed";
Teamleader addItemToUniform "SmokeShellRed";
Teamleader addItemToUniform "B_IR_Grenade";
Teamleader addWeapon "tf_anprc152";
Teamleader selectWeapon (primaryWeapon Teamleader);
};

if (!isNil "Schuetze") then {
removeallweapons Schuetze;
removeallassigneditems Schuetze;
removeHeadgear Schuetze;
removeBackpack Schuetze;
removeVest Schuetze;
removeGoggles Schuetze;

Schuetze addWeapon "ItemMap";
Schuetze addWeapon "ItemWatch";
Schuetze addWeapon "ItemCompass";
Schuetze addWeapon "ItemGPS";
Schuetze addWeapon "H_Bandanna_camo";
Schuetze addWeapon "NVGoggles";
Schuetze addWeapon "Rangefinder";
Schuetze addBackpack "B_TacticalPack_blk";
(backpackContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Schuetze addWeapon "arifle_MX_F";
removeBackpack Schuetze;
Schuetze addPrimaryWeaponItem "acc_pointer_IR";
Schuetze addPrimaryWeaponItem "muzzle_snds_H";
Schuetze addPrimaryWeaponItem "optic_Aco";
Schuetze addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Schuetze);
clearMagazineCargoGlobal (backpackContainer Schuetze);
clearWeaponCargoGlobal (backpackContainer Schuetze);
(backpackContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Schuetze addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Schuetze);
clearMagazineCargoGlobal (vestContainer Schuetze);
clearWeaponCargoGlobal (vestContainer Schuetze);
(vestContainer Schuetze) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Schuetze);
clearMagazineCargoGlobal (uniformContainer Schuetze);
clearWeaponCargoGlobal (uniformContainer Schuetze);
Schuetze addItemToUniform "SmokeShellGreen";
Schuetze addItemToUniform "SmokeShellGreen";
Schuetze addItemToUniform "SmokeShellGreen";
Schuetze addItemToUniform "SmokeShellGreen";
Schuetze addItemToUniform "SmokeShellGreen";
Schuetze addItemToUniform "SmokeShellRed";
Schuetze addItemToUniform "SmokeShellRed";
Schuetze addItemToUniform "SmokeShellRed";
Schuetze addItemToUniform "B_IR_Grenade";
Schuetze addWeapon "tf_anprc152";
Schuetze selectWeapon (primaryWeapon Schuetze);
};

if (!isNil "Schuetze2") then {
removeallweapons Schuetze2;
removeallassigneditems Schuetze2;
removeHeadgear Schuetze2;
removeBackpack Schuetze2;
removeVest Schuetze2;
removeGoggles Schuetze2;

Schuetze2 addWeapon "ItemMap";
Schuetze2 addWeapon "ItemWatch";
Schuetze2 addWeapon "ItemCompass";
Schuetze2 addWeapon "ItemGPS";
Schuetze2 addWeapon "H_Bandanna_camo";
Schuetze2 addWeapon "NVGoggles";
Schuetze2 addWeapon "Rangefinder";
Schuetze2 addBackpack "B_TacticalPack_blk";
(backpackContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Schuetze2 addWeapon "arifle_MX_F";
removeBackpack Schuetze2;
Schuetze2 addPrimaryWeaponItem "acc_pointer_IR";
Schuetze2 addPrimaryWeaponItem "muzzle_snds_H";
Schuetze2 addPrimaryWeaponItem "optic_Aco";
Schuetze2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Schuetze2);
clearMagazineCargoGlobal (backpackContainer Schuetze2);
clearWeaponCargoGlobal (backpackContainer Schuetze2);
(backpackContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",25];
Schuetze2 addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Schuetze2);
clearMagazineCargoGlobal (vestContainer Schuetze2);
clearWeaponCargoGlobal (vestContainer Schuetze2);
(vestContainer Schuetze2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Schuetze2);
clearMagazineCargoGlobal (uniformContainer Schuetze2);
clearWeaponCargoGlobal (uniformContainer Schuetze2);
Schuetze2 addItemToUniform "SmokeShellGreen";
Schuetze2 addItemToUniform "SmokeShellGreen";
Schuetze2 addItemToUniform "SmokeShellGreen";
Schuetze2 addItemToUniform "SmokeShellGreen";
Schuetze2 addItemToUniform "SmokeShellGreen";
Schuetze2 addItemToUniform "SmokeShellRed";
Schuetze2 addItemToUniform "SmokeShellRed";
Schuetze2 addItemToUniform "SmokeShellRed";
Schuetze2 addItemToUniform "B_IR_Grenade";
Schuetze2 addWeapon "tf_anprc152";
Schuetze2 selectWeapon (primaryWeapon Schuetze2);
};

if (!isNil "Marksman") then {
removeallweapons Marksman;
removeallassigneditems Marksman;
removeHeadgear Marksman;
removeBackpack Marksman;
removeVest Marksman;
removeGoggles Marksman;

Marksman addWeapon "ItemMap";
Marksman addWeapon "ItemWatch";
Marksman addWeapon "ItemCompass";
Marksman addWeapon "ItemGPS";
Marksman addWeapon "H_Bandanna_camo";
Marksman addWeapon "NVGoggles";
Marksman addWeapon "Rangefinder";
Marksman addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
Marksman addWeapon "srifle_EBR_F";
removeBackpack Marksman;
Marksman addPrimaryWeaponItem "acc_pointer_IR";
Marksman addPrimaryWeaponItem "muzzle_snds_B";
Marksman addPrimaryWeaponItem "optic_NVS";
Marksman addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Marksman);
clearMagazineCargoGlobal (backpackContainer Marksman);
clearWeaponCargoGlobal (backpackContainer Marksman);
(backpackContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",20];
Marksman addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Marksman);
clearMagazineCargoGlobal (vestContainer Marksman);
clearWeaponCargoGlobal (vestContainer Marksman);
(vestContainer Marksman) addmagazinecargoGlobal ["20Rnd_762x51_Mag",14];
clearItemCargoGlobal (uniformContainer Marksman);
clearMagazineCargoGlobal (uniformContainer Marksman);
clearWeaponCargoGlobal (uniformContainer Marksman);
Marksman addItemToUniform "SmokeShellGreen";
Marksman addItemToUniform "SmokeShellGreen";
Marksman addItemToUniform "SmokeShellGreen";
Marksman addItemToUniform "SmokeShellGreen";
Marksman addItemToUniform "SmokeShellGreen";
Marksman addItemToUniform "SmokeShellRed";
Marksman addItemToUniform "SmokeShellRed";
Marksman addItemToUniform "SmokeShellRed";
Marksman addItemToUniform "B_IR_Grenade";
Marksman addWeapon "tf_anprc152";
Marksman selectWeapon (primaryWeapon Marksman);
};

if (!isNil "Sprengmeister") then {
removeallweapons Sprengmeister;
removeallassigneditems Sprengmeister;
removeHeadgear Sprengmeister;
removeBackpack Sprengmeister;
removeVest Sprengmeister;
removeGoggles Sprengmeister;

Sprengmeister addWeapon "ItemMap";
Sprengmeister addWeapon "ItemWatch";
Sprengmeister addWeapon "ItemCompass";
Sprengmeister addWeapon "ItemGPS";
Sprengmeister addWeapon "H_Bandanna_camo";
Sprengmeister addWeapon "NVGoggles";
Sprengmeister addWeapon "Rangefinder";
Sprengmeister addBackpack "B_TacticalPack_blk";
(backpackContainer Sprengmeister) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Sprengmeister addWeapon "arifle_MX_F";
removeBackpack Sprengmeister;
Sprengmeister addPrimaryWeaponItem "acc_pointer_IR";
Sprengmeister addPrimaryWeaponItem "muzzle_snds_H";
Sprengmeister addPrimaryWeaponItem "optic_Aco";
Sprengmeister addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Sprengmeister);
clearMagazineCargoGlobal (backpackContainer Sprengmeister);
clearWeaponCargoGlobal (backpackContainer Sprengmeister);
Sprengmeister addItemToBackpack "SatchelCharge_Remote_Mag";
Sprengmeister addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Sprengmeister);
clearMagazineCargoGlobal (vestContainer Sprengmeister);
clearWeaponCargoGlobal (vestContainer Sprengmeister);
(vestContainer Sprengmeister) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Sprengmeister);
clearMagazineCargoGlobal (uniformContainer Sprengmeister);
clearWeaponCargoGlobal (uniformContainer Sprengmeister);
Sprengmeister addItemToUniform "SmokeShellGreen";
Sprengmeister addItemToUniform "SmokeShellGreen";
Sprengmeister addItemToUniform "SmokeShellGreen";
Sprengmeister addItemToUniform "SmokeShellGreen";
Sprengmeister addItemToUniform "SmokeShellGreen";
Sprengmeister addItemToUniform "SmokeShellRed";
Sprengmeister addItemToUniform "SmokeShellRed";
Sprengmeister addItemToUniform "SmokeShellRed";
Sprengmeister addItemToUniform "B_IR_Grenade";
Sprengmeister addWeapon "tf_anprc152";
Sprengmeister selectWeapon (primaryWeapon Sprengmeister);
};

if (!isNil "Marksman2") then {
removeallweapons Marksman2;
removeallassigneditems Marksman2;
removeHeadgear Marksman2;
removeBackpack Marksman2;
removeVest Marksman2;
removeGoggles Marksman2;

Marksman2 addWeapon "ItemMap";
Marksman2 addWeapon "ItemWatch";
Marksman2 addWeapon "ItemCompass";
Marksman2 addWeapon "ItemGPS";
Marksman2 addWeapon "H_Bandanna_camo";
Marksman2 addWeapon "NVGoggles";
Marksman2 addWeapon "Rangefinder";
Marksman2 addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
Marksman2 addWeapon "srifle_EBR_F";
removeBackpack Marksman2;
Marksman2 addPrimaryWeaponItem "acc_pointer_IR";
Marksman2 addPrimaryWeaponItem "muzzle_snds_B";
Marksman2 addPrimaryWeaponItem "optic_NVS";
Marksman2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Marksman2);
clearMagazineCargoGlobal (backpackContainer Marksman2);
clearWeaponCargoGlobal (backpackContainer Marksman2);
(backpackContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",20];
Marksman2 addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Marksman2);
clearMagazineCargoGlobal (vestContainer Marksman2);
clearWeaponCargoGlobal (vestContainer Marksman2);
(vestContainer Marksman2) addmagazinecargoGlobal ["20Rnd_762x51_Mag",14];
clearItemCargoGlobal (uniformContainer Marksman2);
clearMagazineCargoGlobal (uniformContainer Marksman2);
clearWeaponCargoGlobal (uniformContainer Marksman2);
Marksman2 addItemToUniform "SmokeShellGreen";
Marksman2 addItemToUniform "SmokeShellGreen";
Marksman2 addItemToUniform "SmokeShellGreen";
Marksman2 addItemToUniform "SmokeShellGreen";
Marksman2 addItemToUniform "SmokeShellGreen";
Marksman2 addItemToUniform "SmokeShellRed";
Marksman2 addItemToUniform "SmokeShellRed";
Marksman2 addItemToUniform "SmokeShellRed";
Marksman2 addItemToUniform "B_IR_Grenade";
Marksman2 addWeapon "tf_anprc152";
Marksman2 selectWeapon (primaryWeapon Marksman2);
};

if (!isNil "Sprengmeister2") then {
removeallweapons Sprengmeister2;
removeallassigneditems Sprengmeister2;
removeHeadgear Sprengmeister2;
removeBackpack Sprengmeister2;
removeVest Sprengmeister2;
removeGoggles Sprengmeister2;

Sprengmeister2 addWeapon "ItemMap";
Sprengmeister2 addWeapon "ItemWatch";
Sprengmeister2 addWeapon "ItemCompass";
Sprengmeister2 addWeapon "ItemGPS";
Sprengmeister2 addWeapon "H_Bandanna_camo";
Sprengmeister2 addWeapon "NVGoggles";
Sprengmeister2 addWeapon "Rangefinder";
Sprengmeister2 addBackpack "B_TacticalPack_blk";
(backpackContainer Sprengmeister2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Sprengmeister2 addWeapon "arifle_MX_F";
removeBackpack Sprengmeister2;
Sprengmeister2 addPrimaryWeaponItem "acc_pointer_IR";
Sprengmeister2 addPrimaryWeaponItem "muzzle_snds_H";
Sprengmeister2 addPrimaryWeaponItem "optic_Aco";
Sprengmeister2 addBackpack "B_FieldPack_ocamo";
clearItemCargoGlobal (backpackContainer Sprengmeister2);
clearMagazineCargoGlobal (backpackContainer Sprengmeister2);
clearWeaponCargoGlobal (backpackContainer Sprengmeister2);
Sprengmeister2 addItemToBackpack "SatchelCharge_Remote_Mag";
Sprengmeister2 addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister2 addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister2 addItemToBackpack "DemoCharge_Remote_Mag";
Sprengmeister2 addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer Sprengmeister2);
clearMagazineCargoGlobal (vestContainer Sprengmeister2);
clearWeaponCargoGlobal (vestContainer Sprengmeister2);
(vestContainer Sprengmeister2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",17];
clearItemCargoGlobal (uniformContainer Sprengmeister2);
clearMagazineCargoGlobal (uniformContainer Sprengmeister2);
clearWeaponCargoGlobal (uniformContainer Sprengmeister2);
Sprengmeister2 addItemToUniform "SmokeShellGreen";
Sprengmeister2 addItemToUniform "SmokeShellGreen";
Sprengmeister2 addItemToUniform "SmokeShellGreen";
Sprengmeister2 addItemToUniform "SmokeShellGreen";
Sprengmeister2 addItemToUniform "SmokeShellGreen";
Sprengmeister2 addItemToUniform "SmokeShellRed";
Sprengmeister2 addItemToUniform "SmokeShellRed";
Sprengmeister2 addItemToUniform "SmokeShellRed";
Sprengmeister2 addItemToUniform "B_IR_Grenade";
Sprengmeister2 addWeapon "tf_anprc152";
Sprengmeister2 selectWeapon (primaryWeapon Sprengmeister2);
};

