/*
* Generated by LEA for Arma 3
* Version: 2.0.18
* Tue Jun 10 08:47:48 CEST 2014
* 
* Call the script: _dummy = this execvm "nightvision.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this addweaponcargoGlobal ["srifle_DMR_01_F",1];
  _this addmagazinecargoGlobal ["10Rnd_762x51_Mag",10];
  _this addmagazinecargoGlobal ["Chemlight_yellow",15];
  _this addmagazinecargoGlobal ["Chemlight_blue",15];
  _this addmagazinecargoGlobal ["SmokeShellGreen",15];
  _this addmagazinecargoGlobal ["SmokeShell",15];
  _this addmagazinecargoGlobal ["SmokeShellBlue",15];
  _this addmagazinecargoGlobal ["SmokeShellRed",15];
  _this addmagazinecargoGlobal ["Chemlight_red",15];
  _this addmagazinecargoGlobal ["Chemlight_green",15];
  _this additemcargoGlobal ["x39_medikit",15];
  _this additemcargoGlobal ["x39_bandage",20];
  _this additemcargoGlobal ["Rangefinder",1];
  _this additemcargoGlobal ["x39_morphine",20];
  _this additemcargoGlobal ["optic_Hamr",1];
  _this additemcargoGlobal ["NVGoggles_OPFOR",15];
  _this additemcargoGlobal ["optic_NVS",1];
  _this additemcargoGlobal ["Binocular",2];
  _this additemcargoGlobal ["x39_defibrillator",2];
  _this additemcargoGlobal ["x39_bloodbag",10];
  _this additemcargoGlobal ["x39_epinephrine",20];
  _this additemcargoGlobal ["x39_tourniquet",20];
};
