/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sat May 10 00:36:08 CEST 2014
* Mission file name: [FS]co11_Stratis_going_beserk.Stratis
* Mission name: [FS]co11_Stratis_going_beserk.Stratis
* Required mods:
* + ArmA 3
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutSingleplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal trans2;
  clearmagazinecargoGlobal trans2;
  clearitemcargoGlobal trans2;

  trans2 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",30];
  trans2 additemcargoGlobal ["FirstAidKit",10];
  trans2 additemcargoGlobal ["Toolkit",5];

  clearweaponcargoGlobal unit_67_164;
  clearmagazinecargoGlobal unit_67_164;
  clearitemcargoGlobal unit_67_164;

  unit_67_164 addweaponcargoGlobal ["arifle_MXC_F",10];
  unit_67_164 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",50];
  unit_67_164 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",30];
  unit_67_164 additemcargoGlobal ["optic_Arco",10];

  clearweaponcargoGlobal unit_67_165;
  clearmagazinecargoGlobal unit_67_165;
  clearitemcargoGlobal unit_67_165;

  unit_67_165 addweaponcargoGlobal ["arifle_MXC_F",10];
  unit_67_165 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",50];
  unit_67_165 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",30];
  unit_67_165 additemcargoGlobal ["optic_Arco",10];

  clearweaponcargoGlobal unit_67_166;
  clearmagazinecargoGlobal unit_67_166;
  clearitemcargoGlobal unit_67_166;

  unit_67_166 addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",20];
  unit_67_166 addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",20];
  unit_67_166 addmagazinecargoGlobal ["UGL_FlareGreen_F",10];
  unit_67_166 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  unit_67_166 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",50];
  unit_67_166 addmagazinecargoGlobal ["SmokeShellGreen",20];
  unit_67_166 addmagazinecargoGlobal ["HandGrenade",15];
  unit_67_166 addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",20];
  unit_67_166 addmagazinecargoGlobal ["UGL_FlareRed_F",10];
  unit_67_166 addmagazinecargoGlobal ["SmokeShellRed",20];
  unit_67_166 additemcargoGlobal ["FirstAidKit",50];
  unit_67_166 additemcargoGlobal ["optic_ACO_grn",10];
  unit_67_166 additemcargoGlobal ["Toolkit",15];
  unit_67_166 additemcargoGlobal ["optic_Arco",10];

  clearweaponcargoGlobal unit_67_167;
  clearmagazinecargoGlobal unit_67_167;
  clearitemcargoGlobal unit_67_167;

  unit_67_167 addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",20];
  unit_67_167 addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",20];
  unit_67_167 addmagazinecargoGlobal ["UGL_FlareGreen_F",10];
  unit_67_167 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  unit_67_167 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",50];
  unit_67_167 addmagazinecargoGlobal ["SmokeShellGreen",20];
  unit_67_167 addmagazinecargoGlobal ["HandGrenade",15];
  unit_67_167 addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",20];
  unit_67_167 addmagazinecargoGlobal ["UGL_FlareRed_F",10];
  unit_67_167 addmagazinecargoGlobal ["SmokeShellRed",20];
  unit_67_167 additemcargoGlobal ["FirstAidKit",50];
  unit_67_167 additemcargoGlobal ["optic_ACO_grn",10];
  unit_67_167 additemcargoGlobal ["Toolkit",15];
  unit_67_167 additemcargoGlobal ["optic_Arco",10];

  clearweaponcargoGlobal trans1;
  clearmagazinecargoGlobal trans1;
  clearitemcargoGlobal trans1;

  trans1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",30];
  trans1 additemcargoGlobal ["FirstAidKit",10];
  trans1 additemcargoGlobal ["Toolkit",5];

//Empty, nothing to do. unit car1

/**
* Loadout for soldiers units
*/

removeallweapons unit_0_0;
removeallassigneditems unit_0_0;
removeHeadgear unit_0_0;
removeBackpack unit_0_0;
removeVest unit_0_0;

unit_0_0 addWeapon "ItemMap";
unit_0_0 addWeapon "ItemWatch";
unit_0_0 addWeapon "ItemCompass";
unit_0_0 addWeapon "ItemGPS";
unit_0_0 addWeapon "H_HelmetB_paint";
unit_0_0 addWeapon "NVGoggles_OPFOR";
unit_0_0 addWeapon "Binocular";
unit_0_0 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_0_0 addWeapon "arifle_MX_GL_F";
removeBackpack unit_0_0;
unit_0_0 addPrimaryWeaponItem "optic_Arco";
unit_0_0 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_0_0);
clearMagazineCargoGlobal (backpackContainer unit_0_0);
clearWeaponCargoGlobal (backpackContainer unit_0_0);
unit_0_0 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_0_0);
clearMagazineCargoGlobal (vestContainer unit_0_0);
clearWeaponCargoGlobal (vestContainer unit_0_0);
(vestContainer unit_0_0) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_0_0) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_0_0) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_0_0);
clearMagazineCargoGlobal (uniformContainer unit_0_0);
clearWeaponCargoGlobal (uniformContainer unit_0_0);
(uniformContainer unit_0_0) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_0_0) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_0_0) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_0_0 addWeapon "tf_rf7800str";
unit_0_0 selectWeapon (primaryWeapon unit_0_0);

removeallweapons unit_0_1;
removeallassigneditems unit_0_1;
removeHeadgear unit_0_1;
removeBackpack unit_0_1;
removeVest unit_0_1;

unit_0_1 addWeapon "ItemMap";
unit_0_1 addWeapon "ItemWatch";
unit_0_1 addWeapon "ItemCompass";
unit_0_1 addWeapon "ItemGPS";
unit_0_1 addWeapon "H_HelmetB_paint";
unit_0_1 addWeapon "NVGoggles_OPFOR";
unit_0_1 addWeapon "Binocular";
unit_0_1 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_0_1 addWeapon "arifle_MX_GL_F";
removeBackpack unit_0_1;
unit_0_1 addPrimaryWeaponItem "optic_Arco";
unit_0_1 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_0_1);
clearMagazineCargoGlobal (backpackContainer unit_0_1);
clearWeaponCargoGlobal (backpackContainer unit_0_1);
unit_0_1 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_0_1);
clearMagazineCargoGlobal (vestContainer unit_0_1);
clearWeaponCargoGlobal (vestContainer unit_0_1);
(vestContainer unit_0_1) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_0_1) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_0_1) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_0_1) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_0_1) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_0_1);
clearMagazineCargoGlobal (uniformContainer unit_0_1);
clearWeaponCargoGlobal (uniformContainer unit_0_1);
(uniformContainer unit_0_1) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_0_1) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_0_1) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_0_1 addWeapon "tf_rf7800str";
unit_0_1 selectWeapon (primaryWeapon unit_0_1);

removeallweapons unit_2_12;
removeallassigneditems unit_2_12;
removeHeadgear unit_2_12;
removeBackpack unit_2_12;
removeVest unit_2_12;

unit_2_12 addWeapon "ItemMap";
unit_2_12 addWeapon "ItemWatch";
unit_2_12 addWeapon "ItemCompass";
unit_2_12 addWeapon "ItemGPS";
unit_2_12 addWeapon "H_HelmetB_paint";
unit_2_12 addWeapon "NVGoggles_OPFOR";
unit_2_12 addWeapon "Binocular";
unit_2_12 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_2_12) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_2_12 addWeapon "arifle_MX_GL_F";
removeBackpack unit_2_12;
unit_2_12 addPrimaryWeaponItem "optic_Arco";
unit_2_12 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_2_12);
clearMagazineCargoGlobal (backpackContainer unit_2_12);
clearWeaponCargoGlobal (backpackContainer unit_2_12);
unit_2_12 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_2_12);
clearMagazineCargoGlobal (vestContainer unit_2_12);
clearWeaponCargoGlobal (vestContainer unit_2_12);
(vestContainer unit_2_12) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_2_12) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_2_12) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_2_12) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_2_12) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_2_12);
clearMagazineCargoGlobal (uniformContainer unit_2_12);
clearWeaponCargoGlobal (uniformContainer unit_2_12);
(uniformContainer unit_2_12) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_2_12) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_2_12) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_2_12 addWeapon "tf_rf7800str";
unit_2_12 selectWeapon (primaryWeapon unit_2_12);

removeallweapons unit_3_13;
removeallassigneditems unit_3_13;
removeHeadgear unit_3_13;
removeBackpack unit_3_13;
removeVest unit_3_13;

unit_3_13 addWeapon "ItemMap";
unit_3_13 addWeapon "ItemWatch";
unit_3_13 addWeapon "ItemCompass";
unit_3_13 addWeapon "ItemGPS";
unit_3_13 addWeapon "H_HelmetB_paint";
unit_3_13 addWeapon "NVGoggles_OPFOR";
unit_3_13 addWeapon "Binocular";
unit_3_13 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_13) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_3_13 addWeapon "arifle_MX_GL_F";
removeBackpack unit_3_13;
unit_3_13 addPrimaryWeaponItem "optic_Arco";
unit_3_13 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_3_13);
clearMagazineCargoGlobal (backpackContainer unit_3_13);
clearWeaponCargoGlobal (backpackContainer unit_3_13);
unit_3_13 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_3_13);
clearMagazineCargoGlobal (vestContainer unit_3_13);
clearWeaponCargoGlobal (vestContainer unit_3_13);
(vestContainer unit_3_13) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_3_13) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_3_13) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_3_13) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_3_13) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_3_13);
clearMagazineCargoGlobal (uniformContainer unit_3_13);
clearWeaponCargoGlobal (uniformContainer unit_3_13);
(uniformContainer unit_3_13) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_3_13) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_3_13) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_3_13 addWeapon "tf_rf7800str";
unit_3_13 selectWeapon (primaryWeapon unit_3_13);

removeallweapons unit_14_40;
removeallassigneditems unit_14_40;
removeHeadgear unit_14_40;
removeBackpack unit_14_40;
removeVest unit_14_40;

unit_14_40 addWeapon "ItemMap";
unit_14_40 addWeapon "ItemWatch";
unit_14_40 addWeapon "ItemCompass";
unit_14_40 addWeapon "ItemGPS";
unit_14_40 addWeapon "H_HelmetB_paint";
unit_14_40 addWeapon "NVGoggles";
unit_14_40 addWeapon "Rangefinder";
unit_14_40 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_40) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_40 addWeapon "arifle_MX_GL_F";
removeBackpack unit_14_40;
unit_14_40 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_40 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_14_40);
clearMagazineCargoGlobal (backpackContainer unit_14_40);
clearWeaponCargoGlobal (backpackContainer unit_14_40);
unit_14_40 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_14_40);
clearMagazineCargoGlobal (vestContainer unit_14_40);
clearWeaponCargoGlobal (vestContainer unit_14_40);
(vestContainer unit_14_40) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_14_40) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",6];
(vestContainer unit_14_40) addmagazinecargoGlobal ["UGL_FlareCIR_F",3];
clearItemCargoGlobal (uniformContainer unit_14_40);
clearMagazineCargoGlobal (uniformContainer unit_14_40);
clearWeaponCargoGlobal (uniformContainer unit_14_40);
(uniformContainer unit_14_40) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_40) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_40) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_40 addWeapon "tf_rf7800str";
unit_14_40 selectWeapon (primaryWeapon unit_14_40);


unit_14_41 addWeapon "ItemMap";
unit_14_41 addWeapon "ItemWatch";
unit_14_41 addWeapon "ItemCompass";
unit_14_41 addWeapon "ItemGPS";
unit_14_41 addWeapon "H_HelmetB";
unit_14_41 addWeapon "NVGoggles";
unit_14_41 addWeapon "Binocular";
unit_14_41 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_41) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_41 addWeapon "arifle_MX_F";
removeBackpack unit_14_41;
unit_14_41 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_41 addVest "V_Chestrig_khk";
clearItemCargoGlobal (vestContainer unit_14_41);
clearMagazineCargoGlobal (vestContainer unit_14_41);
clearWeaponCargoGlobal (vestContainer unit_14_41);
(vestContainer unit_14_41) additemcargoGlobal ["FirstAidKit",2];
(vestContainer unit_14_41) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
clearItemCargoGlobal (uniformContainer unit_14_41);
clearMagazineCargoGlobal (uniformContainer unit_14_41);
clearWeaponCargoGlobal (uniformContainer unit_14_41);
(uniformContainer unit_14_41) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_41) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_41) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_41 addWeapon "tf_rf7800str";
unit_14_41 selectWeapon (primaryWeapon unit_14_41);


unit_14_42 addWeapon "ItemMap";
unit_14_42 addWeapon "ItemWatch";
unit_14_42 addWeapon "ItemCompass";
unit_14_42 addWeapon "ItemGPS";
unit_14_42 addWeapon "H_HelmetB";
unit_14_42 addWeapon "NVGoggles";
unit_14_42 addWeapon "Binocular";
unit_14_42 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_42) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_42 addWeapon "arifle_MX_F";
removeBackpack unit_14_42;
unit_14_42 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_42 addVest "V_Chestrig_khk";
clearItemCargoGlobal (vestContainer unit_14_42);
clearMagazineCargoGlobal (vestContainer unit_14_42);
clearWeaponCargoGlobal (vestContainer unit_14_42);
(vestContainer unit_14_42) additemcargoGlobal ["FirstAidKit",2];
(vestContainer unit_14_42) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
clearItemCargoGlobal (uniformContainer unit_14_42);
clearMagazineCargoGlobal (uniformContainer unit_14_42);
clearWeaponCargoGlobal (uniformContainer unit_14_42);
(uniformContainer unit_14_42) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_42) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_42) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_42 addWeapon "tf_rf7800str";
unit_14_42 selectWeapon (primaryWeapon unit_14_42);

removeallweapons unit_59_140;
removeallassigneditems unit_59_140;
removeHeadgear unit_59_140;
removeBackpack unit_59_140;
removeVest unit_59_140;

unit_59_140 addWeapon "ItemMap";
unit_59_140 addWeapon "ItemWatch";
unit_59_140 addWeapon "ItemCompass";
unit_59_140 addWeapon "ItemGPS";
unit_59_140 addWeapon "H_HelmetB_paint";
unit_59_140 addWeapon "NVGoggles_OPFOR";
unit_59_140 addWeapon "Binocular";
unit_59_140 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_59_140) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_59_140 addWeapon "arifle_MX_GL_F";
removeBackpack unit_59_140;
unit_59_140 addPrimaryWeaponItem "optic_Arco";
unit_59_140 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_59_140);
clearMagazineCargoGlobal (backpackContainer unit_59_140);
clearWeaponCargoGlobal (backpackContainer unit_59_140);
unit_59_140 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_59_140);
clearMagazineCargoGlobal (vestContainer unit_59_140);
clearWeaponCargoGlobal (vestContainer unit_59_140);
(vestContainer unit_59_140) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_59_140) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_59_140) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_59_140) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_59_140) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_59_140);
clearMagazineCargoGlobal (uniformContainer unit_59_140);
clearWeaponCargoGlobal (uniformContainer unit_59_140);
(uniformContainer unit_59_140) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_59_140) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_59_140) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_59_140 addWeapon "tf_rf7800str";
unit_59_140 selectWeapon (primaryWeapon unit_59_140);

removeallweapons unit_60_141;
removeallassigneditems unit_60_141;
removeHeadgear unit_60_141;
removeBackpack unit_60_141;
removeVest unit_60_141;

unit_60_141 addWeapon "ItemMap";
unit_60_141 addWeapon "ItemWatch";
unit_60_141 addWeapon "ItemCompass";
unit_60_141 addWeapon "ItemGPS";
unit_60_141 addWeapon "H_HelmetB_paint";
unit_60_141 addWeapon "NVGoggles_OPFOR";
unit_60_141 addWeapon "Binocular";
unit_60_141 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_60_141) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_60_141 addWeapon "arifle_MX_GL_F";
removeBackpack unit_60_141;
unit_60_141 addPrimaryWeaponItem "optic_Arco";
unit_60_141 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_60_141);
clearMagazineCargoGlobal (backpackContainer unit_60_141);
clearWeaponCargoGlobal (backpackContainer unit_60_141);
unit_60_141 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_60_141);
clearMagazineCargoGlobal (vestContainer unit_60_141);
clearWeaponCargoGlobal (vestContainer unit_60_141);
(vestContainer unit_60_141) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_60_141) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_60_141) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_60_141) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_60_141) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_60_141);
clearMagazineCargoGlobal (uniformContainer unit_60_141);
clearWeaponCargoGlobal (uniformContainer unit_60_141);
(uniformContainer unit_60_141) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_60_141) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_60_141) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_60_141 addWeapon "tf_rf7800str";
unit_60_141 selectWeapon (primaryWeapon unit_60_141);

removeallweapons unit_61_142;
removeallassigneditems unit_61_142;
removeHeadgear unit_61_142;
removeBackpack unit_61_142;
removeVest unit_61_142;

unit_61_142 addWeapon "ItemMap";
unit_61_142 addWeapon "ItemWatch";
unit_61_142 addWeapon "ItemCompass";
unit_61_142 addWeapon "ItemGPS";
unit_61_142 addWeapon "H_HelmetB_paint";
unit_61_142 addWeapon "NVGoggles_OPFOR";
unit_61_142 addWeapon "Binocular";
unit_61_142 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_61_142) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_61_142 addWeapon "arifle_MX_GL_F";
removeBackpack unit_61_142;
unit_61_142 addPrimaryWeaponItem "optic_Arco";
unit_61_142 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_61_142);
clearMagazineCargoGlobal (backpackContainer unit_61_142);
clearWeaponCargoGlobal (backpackContainer unit_61_142);
unit_61_142 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_61_142);
clearMagazineCargoGlobal (vestContainer unit_61_142);
clearWeaponCargoGlobal (vestContainer unit_61_142);
(vestContainer unit_61_142) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_61_142) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_61_142) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_61_142) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_61_142) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_61_142);
clearMagazineCargoGlobal (uniformContainer unit_61_142);
clearWeaponCargoGlobal (uniformContainer unit_61_142);
(uniformContainer unit_61_142) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_61_142) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_61_142) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_61_142 addWeapon "tf_rf7800str";
unit_61_142 selectWeapon (primaryWeapon unit_61_142);

removeallweapons unit_62_143;
removeallassigneditems unit_62_143;
removeHeadgear unit_62_143;
removeBackpack unit_62_143;
removeVest unit_62_143;

unit_62_143 addWeapon "ItemMap";
unit_62_143 addWeapon "ItemWatch";
unit_62_143 addWeapon "ItemCompass";
unit_62_143 addWeapon "ItemGPS";
unit_62_143 addWeapon "H_HelmetB_paint";
unit_62_143 addWeapon "NVGoggles_OPFOR";
unit_62_143 addWeapon "Binocular";
unit_62_143 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_62_143) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_62_143 addWeapon "arifle_MX_GL_F";
removeBackpack unit_62_143;
unit_62_143 addPrimaryWeaponItem "optic_Arco";
unit_62_143 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_62_143);
clearMagazineCargoGlobal (backpackContainer unit_62_143);
clearWeaponCargoGlobal (backpackContainer unit_62_143);
unit_62_143 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_62_143);
clearMagazineCargoGlobal (vestContainer unit_62_143);
clearWeaponCargoGlobal (vestContainer unit_62_143);
(vestContainer unit_62_143) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_62_143) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_62_143) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_62_143) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_62_143) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_62_143);
clearMagazineCargoGlobal (uniformContainer unit_62_143);
clearWeaponCargoGlobal (uniformContainer unit_62_143);
(uniformContainer unit_62_143) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_62_143) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_62_143) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_62_143 addWeapon "tf_rf7800str";
unit_62_143 selectWeapon (primaryWeapon unit_62_143);

removeallweapons unit_63_144;
removeallassigneditems unit_63_144;
removeHeadgear unit_63_144;
removeBackpack unit_63_144;
removeVest unit_63_144;

unit_63_144 addWeapon "ItemMap";
unit_63_144 addWeapon "ItemWatch";
unit_63_144 addWeapon "ItemCompass";
unit_63_144 addWeapon "ItemGPS";
unit_63_144 addWeapon "H_HelmetB_paint";
unit_63_144 addWeapon "NVGoggles_OPFOR";
unit_63_144 addWeapon "Binocular";
unit_63_144 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_63_144) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_63_144 addWeapon "arifle_MX_GL_F";
removeBackpack unit_63_144;
unit_63_144 addPrimaryWeaponItem "optic_Arco";
unit_63_144 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_63_144);
clearMagazineCargoGlobal (backpackContainer unit_63_144);
clearWeaponCargoGlobal (backpackContainer unit_63_144);
unit_63_144 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_63_144);
clearMagazineCargoGlobal (vestContainer unit_63_144);
clearWeaponCargoGlobal (vestContainer unit_63_144);
(vestContainer unit_63_144) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_63_144) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_63_144) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_63_144) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_63_144) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_63_144);
clearMagazineCargoGlobal (uniformContainer unit_63_144);
clearWeaponCargoGlobal (uniformContainer unit_63_144);
(uniformContainer unit_63_144) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_63_144) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_63_144) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_63_144 addWeapon "tf_rf7800str";
unit_63_144 selectWeapon (primaryWeapon unit_63_144);

removeallweapons unit_64_145;
removeallassigneditems unit_64_145;
removeHeadgear unit_64_145;
removeBackpack unit_64_145;
removeVest unit_64_145;

unit_64_145 addWeapon "ItemMap";
unit_64_145 addWeapon "ItemWatch";
unit_64_145 addWeapon "ItemCompass";
unit_64_145 addWeapon "ItemGPS";
unit_64_145 addWeapon "H_HelmetB_paint";
unit_64_145 addWeapon "NVGoggles_OPFOR";
unit_64_145 addWeapon "Binocular";
unit_64_145 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_64_145) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_64_145 addWeapon "arifle_MX_GL_F";
removeBackpack unit_64_145;
unit_64_145 addPrimaryWeaponItem "optic_Arco";
unit_64_145 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_64_145);
clearMagazineCargoGlobal (backpackContainer unit_64_145);
clearWeaponCargoGlobal (backpackContainer unit_64_145);
unit_64_145 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_64_145);
clearMagazineCargoGlobal (vestContainer unit_64_145);
clearWeaponCargoGlobal (vestContainer unit_64_145);
(vestContainer unit_64_145) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_64_145) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_64_145) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_64_145) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_64_145) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_64_145);
clearMagazineCargoGlobal (uniformContainer unit_64_145);
clearWeaponCargoGlobal (uniformContainer unit_64_145);
(uniformContainer unit_64_145) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_64_145) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_64_145) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_64_145 addWeapon "tf_rf7800str";
unit_64_145 selectWeapon (primaryWeapon unit_64_145);

removeallweapons unit_65_146;
removeallassigneditems unit_65_146;
removeHeadgear unit_65_146;
removeBackpack unit_65_146;
removeVest unit_65_146;

unit_65_146 addWeapon "ItemMap";
unit_65_146 addWeapon "ItemWatch";
unit_65_146 addWeapon "ItemCompass";
unit_65_146 addWeapon "ItemGPS";
unit_65_146 addWeapon "H_HelmetB_paint";
unit_65_146 addWeapon "NVGoggles_OPFOR";
unit_65_146 addWeapon "Rangefinder";
unit_65_146 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_146) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_146 addWeapon "arifle_MX_GL_F";
removeBackpack unit_65_146;
unit_65_146 addPrimaryWeaponItem "optic_Arco";
unit_65_146 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_65_146);
clearMagazineCargoGlobal (backpackContainer unit_65_146);
clearWeaponCargoGlobal (backpackContainer unit_65_146);
unit_65_146 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_146);
clearMagazineCargoGlobal (vestContainer unit_65_146);
clearWeaponCargoGlobal (vestContainer unit_65_146);
(vestContainer unit_65_146) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_146) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_146) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_146) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_146) addmagazinecargoGlobal ["UGL_FlareWhite_F",1];
(vestContainer unit_65_146) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_146);
clearMagazineCargoGlobal (uniformContainer unit_65_146);
clearWeaponCargoGlobal (uniformContainer unit_65_146);
(uniformContainer unit_65_146) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_146) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_146) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_146 addWeapon "tf_rf7800str";
unit_65_146 selectWeapon (primaryWeapon unit_65_146);

removeallweapons unit_65_147;
removeallassigneditems unit_65_147;
removeHeadgear unit_65_147;
removeBackpack unit_65_147;
removeVest unit_65_147;

unit_65_147 addWeapon "ItemMap";
unit_65_147 addWeapon "ItemWatch";
unit_65_147 addWeapon "ItemCompass";
unit_65_147 addWeapon "ItemGPS";
unit_65_147 addWeapon "H_HelmetB_paint";
unit_65_147 addWeapon "NVGoggles_OPFOR";
unit_65_147 addWeapon "Binocular";
unit_65_147 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_147) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_147 addWeapon "arifle_MX_GL_F";
removeBackpack unit_65_147;
unit_65_147 addPrimaryWeaponItem "optic_Arco";
unit_65_147 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_65_147);
clearMagazineCargoGlobal (backpackContainer unit_65_147);
clearWeaponCargoGlobal (backpackContainer unit_65_147);
unit_65_147 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_147);
clearMagazineCargoGlobal (vestContainer unit_65_147);
clearWeaponCargoGlobal (vestContainer unit_65_147);
(vestContainer unit_65_147) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_147) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_147) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_147) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_147) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_147);
clearMagazineCargoGlobal (uniformContainer unit_65_147);
clearWeaponCargoGlobal (uniformContainer unit_65_147);
(uniformContainer unit_65_147) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_147) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_147) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_147 addWeapon "tf_rf7800str";
unit_65_147 selectWeapon (primaryWeapon unit_65_147);

removeallweapons unit_65_148;
removeallassigneditems unit_65_148;
removeHeadgear unit_65_148;
removeBackpack unit_65_148;
removeVest unit_65_148;

unit_65_148 addWeapon "ItemMap";
unit_65_148 addWeapon "ItemWatch";
unit_65_148 addWeapon "ItemCompass";
unit_65_148 addWeapon "ItemGPS";
unit_65_148 addWeapon "H_HelmetB";
unit_65_148 addWeapon "NVGoggles";
unit_65_148 addWeapon "Binocular";
unit_65_148 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",1];
unit_65_148 addWeapon "LMG_Mk200_F";
removeBackpack unit_65_148;
unit_65_148 addPrimaryWeaponItem "optic_ACO_grn";
unit_65_148 addVest "V_PlateCarrier2_rgr";
clearItemCargoGlobal (vestContainer unit_65_148);
clearMagazineCargoGlobal (vestContainer unit_65_148);
clearWeaponCargoGlobal (vestContainer unit_65_148);
(vestContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",2];
(vestContainer unit_65_148) addmagazinecargoGlobal ["SmokeShellGreen",5];
(vestContainer unit_65_148) addmagazinecargoGlobal ["HandGrenade",1];
(vestContainer unit_65_148) addmagazinecargoGlobal ["SmokeShellRed",2];
clearItemCargoGlobal (uniformContainer unit_65_148);
clearMagazineCargoGlobal (uniformContainer unit_65_148);
clearWeaponCargoGlobal (uniformContainer unit_65_148);
(uniformContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
unit_65_148 addWeapon "tf_rf7800str";
unit_65_148 selectWeapon (primaryWeapon unit_65_148);

removeallweapons unit_65_149;
removeallassigneditems unit_65_149;
removeHeadgear unit_65_149;
removeBackpack unit_65_149;
removeVest unit_65_149;

unit_65_149 addWeapon "ItemMap";
unit_65_149 addWeapon "ItemWatch";
unit_65_149 addWeapon "ItemCompass";
unit_65_149 addWeapon "ItemGPS";
unit_65_149 addWeapon "H_HelmetB_paint";
unit_65_149 addWeapon "NVGoggles_OPFOR";
unit_65_149 addWeapon "Binocular";
unit_65_149 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_149) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_149 addWeapon "arifle_MX_F";
removeBackpack unit_65_149;
unit_65_149 addPrimaryWeaponItem "optic_Arco";
unit_65_149 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_65_149);
clearMagazineCargoGlobal (backpackContainer unit_65_149);
clearWeaponCargoGlobal (backpackContainer unit_65_149);
(backpackContainer unit_65_149) additemcargoGlobal ["FirstAidKit",20];
unit_65_149 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_149);
clearMagazineCargoGlobal (vestContainer unit_65_149);
clearWeaponCargoGlobal (vestContainer unit_65_149);
(vestContainer unit_65_149) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_149) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_149) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_149) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_149) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_149);
clearMagazineCargoGlobal (uniformContainer unit_65_149);
clearWeaponCargoGlobal (uniformContainer unit_65_149);
(uniformContainer unit_65_149) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_149) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_149) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_149 addWeapon "tf_rf7800str";
unit_65_149 selectWeapon (primaryWeapon unit_65_149);

removeallweapons unit_66_150;
removeallassigneditems unit_66_150;
removeHeadgear unit_66_150;
removeBackpack unit_66_150;
removeVest unit_66_150;

unit_66_150 addWeapon "ItemMap";
unit_66_150 addWeapon "ItemWatch";
unit_66_150 addWeapon "ItemCompass";
unit_66_150 addWeapon "ItemGPS";
unit_66_150 addWeapon "H_HelmetB_paint";
unit_66_150 addWeapon "NVGoggles_OPFOR";
unit_66_150 addWeapon "Rangefinder";
unit_66_150 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_150) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_150 addWeapon "arifle_MX_GL_F";
removeBackpack unit_66_150;
unit_66_150 addPrimaryWeaponItem "optic_Arco";
unit_66_150 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_66_150);
clearMagazineCargoGlobal (backpackContainer unit_66_150);
clearWeaponCargoGlobal (backpackContainer unit_66_150);
unit_66_150 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_150);
clearMagazineCargoGlobal (vestContainer unit_66_150);
clearWeaponCargoGlobal (vestContainer unit_66_150);
(vestContainer unit_66_150) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_150) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_150) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_150) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_150) addmagazinecargoGlobal ["UGL_FlareWhite_F",1];
(vestContainer unit_66_150) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_150);
clearMagazineCargoGlobal (uniformContainer unit_66_150);
clearWeaponCargoGlobal (uniformContainer unit_66_150);
(uniformContainer unit_66_150) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_150) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_150) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_150 addWeapon "tf_rf7800str";
unit_66_150 selectWeapon (primaryWeapon unit_66_150);

removeallweapons unit_66_151;
removeallassigneditems unit_66_151;
removeHeadgear unit_66_151;
removeBackpack unit_66_151;
removeVest unit_66_151;

unit_66_151 addWeapon "ItemMap";
unit_66_151 addWeapon "ItemWatch";
unit_66_151 addWeapon "ItemCompass";
unit_66_151 addWeapon "ItemGPS";
unit_66_151 addWeapon "H_HelmetB_paint";
unit_66_151 addWeapon "NVGoggles_OPFOR";
unit_66_151 addWeapon "Binocular";
unit_66_151 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_151) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_151 addWeapon "arifle_MX_F";
removeBackpack unit_66_151;
unit_66_151 addPrimaryWeaponItem "optic_Arco";
unit_66_151 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_66_151);
clearMagazineCargoGlobal (backpackContainer unit_66_151);
clearWeaponCargoGlobal (backpackContainer unit_66_151);
(backpackContainer unit_66_151) additemcargoGlobal ["FirstAidKit",20];
unit_66_151 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_151);
clearMagazineCargoGlobal (vestContainer unit_66_151);
clearWeaponCargoGlobal (vestContainer unit_66_151);
(vestContainer unit_66_151) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_151) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_151) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_151) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_151) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_151);
clearMagazineCargoGlobal (uniformContainer unit_66_151);
clearWeaponCargoGlobal (uniformContainer unit_66_151);
(uniformContainer unit_66_151) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_151) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_151) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_151 addWeapon "tf_rf7800str";
unit_66_151 selectWeapon (primaryWeapon unit_66_151);

removeallweapons unit_66_152;
removeallassigneditems unit_66_152;
removeHeadgear unit_66_152;
removeBackpack unit_66_152;
removeVest unit_66_152;

unit_66_152 addWeapon "ItemMap";
unit_66_152 addWeapon "ItemWatch";
unit_66_152 addWeapon "ItemCompass";
unit_66_152 addWeapon "ItemGPS";
unit_66_152 addWeapon "H_HelmetB";
unit_66_152 addWeapon "NVGoggles";
unit_66_152 addWeapon "Binocular";
unit_66_152 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",1];
unit_66_152 addWeapon "LMG_Mk200_F";
removeBackpack unit_66_152;
unit_66_152 addPrimaryWeaponItem "optic_ACO_grn";
unit_66_152 addVest "V_PlateCarrier2_rgr";
clearItemCargoGlobal (vestContainer unit_66_152);
clearMagazineCargoGlobal (vestContainer unit_66_152);
clearWeaponCargoGlobal (vestContainer unit_66_152);
(vestContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",2];
(vestContainer unit_66_152) addmagazinecargoGlobal ["SmokeShellGreen",5];
(vestContainer unit_66_152) addmagazinecargoGlobal ["HandGrenade",1];
(vestContainer unit_66_152) addmagazinecargoGlobal ["SmokeShellRed",2];
clearItemCargoGlobal (uniformContainer unit_66_152);
clearMagazineCargoGlobal (uniformContainer unit_66_152);
clearWeaponCargoGlobal (uniformContainer unit_66_152);
(uniformContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
unit_66_152 addWeapon "tf_rf7800str";
unit_66_152 selectWeapon (primaryWeapon unit_66_152);

removeallweapons unit_66_153;
removeallassigneditems unit_66_153;
removeHeadgear unit_66_153;
removeBackpack unit_66_153;
removeVest unit_66_153;

unit_66_153 addWeapon "ItemMap";
unit_66_153 addWeapon "ItemWatch";
unit_66_153 addWeapon "ItemCompass";
unit_66_153 addWeapon "ItemGPS";
unit_66_153 addWeapon "H_HelmetB_paint";
unit_66_153 addWeapon "NVGoggles_OPFOR";
unit_66_153 addWeapon "Binocular";
unit_66_153 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_153) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_153 addWeapon "arifle_MX_GL_F";
removeBackpack unit_66_153;
unit_66_153 addPrimaryWeaponItem "optic_Arco";
unit_66_153 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_66_153);
clearMagazineCargoGlobal (backpackContainer unit_66_153);
clearWeaponCargoGlobal (backpackContainer unit_66_153);
unit_66_153 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_153);
clearMagazineCargoGlobal (vestContainer unit_66_153);
clearWeaponCargoGlobal (vestContainer unit_66_153);
(vestContainer unit_66_153) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_153) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_153) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_153) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_153) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_153);
clearMagazineCargoGlobal (uniformContainer unit_66_153);
clearWeaponCargoGlobal (uniformContainer unit_66_153);
(uniformContainer unit_66_153) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_153) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_153) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_153 addWeapon "tf_rf7800str";
unit_66_153 selectWeapon (primaryWeapon unit_66_153);

removeallweapons y;
removeallassigneditems y;
removeHeadgear y;
removeUniform y;
removeBackpack y;
removeVest y;

if (count weapons y > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons y) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     y selectWeapon (_muzzles select 0);
  }
  else {
     y selectWeapon _type;
  };
};

removeallweapons x;
removeallassigneditems x;
removeHeadgear x;
removeUniform x;
removeBackpack x;
removeVest x;

if (count weapons x > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons x) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     x selectWeapon (_muzzles select 0);
  }
  else {
     x selectWeapon _type;
  };
};

removeallweapons x_1;
removeallassigneditems x_1;
removeHeadgear x_1;
removeUniform x_1;
removeBackpack x_1;
removeVest x_1;

if (count weapons x_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons x_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     x_1 selectWeapon (_muzzles select 0);
  }
  else {
     x_1 selectWeapon _type;
  };
};

removeallweapons x_2;
removeallassigneditems x_2;
removeHeadgear x_2;
removeUniform x_2;
removeBackpack x_2;
removeVest x_2;

if (count weapons x_2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons x_2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     x_2 selectWeapon (_muzzles select 0);
  }
  else {
     x_2 selectWeapon _type;
  };
};

removeallweapons x_1_1;
removeallassigneditems x_1_1;
removeHeadgear x_1_1;
removeUniform x_1_1;
removeBackpack x_1_1;
removeVest x_1_1;

if (count weapons x_1_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons x_1_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     x_1_1 selectWeapon (_muzzles select 0);
  }
  else {
     x_1_1 selectWeapon _type;
  };
};

removeallweapons x_2_1;
removeallassigneditems x_2_1;
removeHeadgear x_2_1;
removeUniform x_2_1;
removeBackpack x_2_1;
removeVest x_2_1;

if (count weapons x_2_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons x_2_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     x_2_1 selectWeapon (_muzzles select 0);
  }
  else {
     x_2_1 selectWeapon _type;
  };
};

