/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sat May 10 00:36:08 CEST 2014
* Mission file name: [FS]co11_Stratis_going_beserk.Stratis
* Mission name: [FS]co11_Stratis_going_beserk.Stratis
* Required mods:
* + ArmA 3
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit car1

/**
* Loadout for soldiers units
*/

if (player == unit_14_40) exitwith {
removeallweapons unit_14_40;
removeallassigneditems unit_14_40;
removeHeadgear unit_14_40;
removeBackpack unit_14_40;
removeVest unit_14_40;

unit_14_40 addWeapon "ItemMap";
unit_14_40 addWeapon "ItemWatch";
unit_14_40 addWeapon "ItemCompass";
unit_14_40 addWeapon "ItemGPS";
unit_14_40 addWeapon "H_HelmetB_paint";
unit_14_40 addWeapon "NVGoggles";
unit_14_40 addWeapon "Rangefinder";
unit_14_40 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_40) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_40 addWeapon "arifle_MX_GL_F";
removeBackpack unit_14_40;
unit_14_40 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_40 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_14_40);
clearMagazineCargoGlobal (backpackContainer unit_14_40);
clearWeaponCargoGlobal (backpackContainer unit_14_40);
unit_14_40 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_14_40);
clearMagazineCargoGlobal (vestContainer unit_14_40);
clearWeaponCargoGlobal (vestContainer unit_14_40);
(vestContainer unit_14_40) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_14_40) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_14_40) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",6];
(vestContainer unit_14_40) addmagazinecargoGlobal ["UGL_FlareCIR_F",3];
clearItemCargoGlobal (uniformContainer unit_14_40);
clearMagazineCargoGlobal (uniformContainer unit_14_40);
clearWeaponCargoGlobal (uniformContainer unit_14_40);
(uniformContainer unit_14_40) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_40) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_40) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_40 addWeapon "tf_rf7800str";
unit_14_40 selectWeapon (primaryWeapon unit_14_40);
};

if (player == unit_14_41) exitwith {

unit_14_41 addWeapon "ItemMap";
unit_14_41 addWeapon "ItemWatch";
unit_14_41 addWeapon "ItemCompass";
unit_14_41 addWeapon "ItemGPS";
unit_14_41 addWeapon "H_HelmetB";
unit_14_41 addWeapon "NVGoggles";
unit_14_41 addWeapon "Binocular";
unit_14_41 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_41) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_41 addWeapon "arifle_MX_F";
removeBackpack unit_14_41;
unit_14_41 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_41 addVest "V_Chestrig_khk";
clearItemCargoGlobal (vestContainer unit_14_41);
clearMagazineCargoGlobal (vestContainer unit_14_41);
clearWeaponCargoGlobal (vestContainer unit_14_41);
(vestContainer unit_14_41) additemcargoGlobal ["FirstAidKit",2];
(vestContainer unit_14_41) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
clearItemCargoGlobal (uniformContainer unit_14_41);
clearMagazineCargoGlobal (uniformContainer unit_14_41);
clearWeaponCargoGlobal (uniformContainer unit_14_41);
(uniformContainer unit_14_41) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_41) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_41) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_41 addWeapon "tf_rf7800str";
unit_14_41 selectWeapon (primaryWeapon unit_14_41);
};

if (player == unit_14_42) exitwith {

unit_14_42 addWeapon "ItemMap";
unit_14_42 addWeapon "ItemWatch";
unit_14_42 addWeapon "ItemCompass";
unit_14_42 addWeapon "ItemGPS";
unit_14_42 addWeapon "H_HelmetB";
unit_14_42 addWeapon "NVGoggles";
unit_14_42 addWeapon "Binocular";
unit_14_42 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_14_42) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_14_42 addWeapon "arifle_MX_F";
removeBackpack unit_14_42;
unit_14_42 addPrimaryWeaponItem "optic_ACO_grn";
unit_14_42 addVest "V_Chestrig_khk";
clearItemCargoGlobal (vestContainer unit_14_42);
clearMagazineCargoGlobal (vestContainer unit_14_42);
clearWeaponCargoGlobal (vestContainer unit_14_42);
(vestContainer unit_14_42) additemcargoGlobal ["FirstAidKit",2];
(vestContainer unit_14_42) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
clearItemCargoGlobal (uniformContainer unit_14_42);
clearMagazineCargoGlobal (uniformContainer unit_14_42);
clearWeaponCargoGlobal (uniformContainer unit_14_42);
(uniformContainer unit_14_42) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_14_42) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_14_42) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_14_42 addWeapon "tf_rf7800str";
unit_14_42 selectWeapon (primaryWeapon unit_14_42);
};

if (player == unit_65_146) exitwith {
removeallweapons unit_65_146;
removeallassigneditems unit_65_146;
removeHeadgear unit_65_146;
removeBackpack unit_65_146;
removeVest unit_65_146;

unit_65_146 addWeapon "ItemMap";
unit_65_146 addWeapon "ItemWatch";
unit_65_146 addWeapon "ItemCompass";
unit_65_146 addWeapon "ItemGPS";
unit_65_146 addWeapon "H_HelmetB_paint";
unit_65_146 addWeapon "NVGoggles_OPFOR";
unit_65_146 addWeapon "Rangefinder";
unit_65_146 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_146) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_146 addWeapon "arifle_MX_GL_F";
removeBackpack unit_65_146;
unit_65_146 addPrimaryWeaponItem "optic_Arco";
unit_65_146 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_65_146);
clearMagazineCargoGlobal (backpackContainer unit_65_146);
clearWeaponCargoGlobal (backpackContainer unit_65_146);
unit_65_146 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_146);
clearMagazineCargoGlobal (vestContainer unit_65_146);
clearWeaponCargoGlobal (vestContainer unit_65_146);
(vestContainer unit_65_146) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_146) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_146) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_146) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_146) addmagazinecargoGlobal ["UGL_FlareWhite_F",1];
(vestContainer unit_65_146) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_146);
clearMagazineCargoGlobal (uniformContainer unit_65_146);
clearWeaponCargoGlobal (uniformContainer unit_65_146);
(uniformContainer unit_65_146) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_146) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_146) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_146 addWeapon "tf_rf7800str";
unit_65_146 selectWeapon (primaryWeapon unit_65_146);
};

if (player == unit_65_147) exitwith {
removeallweapons unit_65_147;
removeallassigneditems unit_65_147;
removeHeadgear unit_65_147;
removeBackpack unit_65_147;
removeVest unit_65_147;

unit_65_147 addWeapon "ItemMap";
unit_65_147 addWeapon "ItemWatch";
unit_65_147 addWeapon "ItemCompass";
unit_65_147 addWeapon "ItemGPS";
unit_65_147 addWeapon "H_HelmetB_paint";
unit_65_147 addWeapon "NVGoggles_OPFOR";
unit_65_147 addWeapon "Binocular";
unit_65_147 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_147) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_147 addWeapon "arifle_MX_GL_F";
removeBackpack unit_65_147;
unit_65_147 addPrimaryWeaponItem "optic_Arco";
unit_65_147 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_65_147);
clearMagazineCargoGlobal (backpackContainer unit_65_147);
clearWeaponCargoGlobal (backpackContainer unit_65_147);
unit_65_147 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_147);
clearMagazineCargoGlobal (vestContainer unit_65_147);
clearWeaponCargoGlobal (vestContainer unit_65_147);
(vestContainer unit_65_147) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_147) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_147) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_147) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_147) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_147);
clearMagazineCargoGlobal (uniformContainer unit_65_147);
clearWeaponCargoGlobal (uniformContainer unit_65_147);
(uniformContainer unit_65_147) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_147) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_147) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_147 addWeapon "tf_rf7800str";
unit_65_147 selectWeapon (primaryWeapon unit_65_147);
};

if (player == unit_65_148) exitwith {
removeallweapons unit_65_148;
removeallassigneditems unit_65_148;
removeHeadgear unit_65_148;
removeBackpack unit_65_148;
removeVest unit_65_148;

unit_65_148 addWeapon "ItemMap";
unit_65_148 addWeapon "ItemWatch";
unit_65_148 addWeapon "ItemCompass";
unit_65_148 addWeapon "ItemGPS";
unit_65_148 addWeapon "H_HelmetB";
unit_65_148 addWeapon "NVGoggles";
unit_65_148 addWeapon "Binocular";
unit_65_148 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",1];
unit_65_148 addWeapon "LMG_Mk200_F";
removeBackpack unit_65_148;
unit_65_148 addPrimaryWeaponItem "optic_ACO_grn";
unit_65_148 addVest "V_PlateCarrier2_rgr";
clearItemCargoGlobal (vestContainer unit_65_148);
clearMagazineCargoGlobal (vestContainer unit_65_148);
clearWeaponCargoGlobal (vestContainer unit_65_148);
(vestContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",2];
(vestContainer unit_65_148) addmagazinecargoGlobal ["SmokeShellGreen",5];
(vestContainer unit_65_148) addmagazinecargoGlobal ["HandGrenade",1];
(vestContainer unit_65_148) addmagazinecargoGlobal ["SmokeShellRed",2];
clearItemCargoGlobal (uniformContainer unit_65_148);
clearMagazineCargoGlobal (uniformContainer unit_65_148);
clearWeaponCargoGlobal (uniformContainer unit_65_148);
(uniformContainer unit_65_148) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
unit_65_148 addWeapon "tf_rf7800str";
unit_65_148 selectWeapon (primaryWeapon unit_65_148);
};

if (player == unit_65_149) exitwith {
removeallweapons unit_65_149;
removeallassigneditems unit_65_149;
removeHeadgear unit_65_149;
removeBackpack unit_65_149;
removeVest unit_65_149;

unit_65_149 addWeapon "ItemMap";
unit_65_149 addWeapon "ItemWatch";
unit_65_149 addWeapon "ItemCompass";
unit_65_149 addWeapon "ItemGPS";
unit_65_149 addWeapon "H_HelmetB_paint";
unit_65_149 addWeapon "NVGoggles_OPFOR";
unit_65_149 addWeapon "Binocular";
unit_65_149 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_65_149) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_65_149 addWeapon "arifle_MX_F";
removeBackpack unit_65_149;
unit_65_149 addPrimaryWeaponItem "optic_Arco";
unit_65_149 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_65_149);
clearMagazineCargoGlobal (backpackContainer unit_65_149);
clearWeaponCargoGlobal (backpackContainer unit_65_149);
(backpackContainer unit_65_149) additemcargoGlobal ["FirstAidKit",20];
unit_65_149 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_65_149);
clearMagazineCargoGlobal (vestContainer unit_65_149);
clearWeaponCargoGlobal (vestContainer unit_65_149);
(vestContainer unit_65_149) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_65_149) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_65_149) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_65_149) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_65_149) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_65_149);
clearMagazineCargoGlobal (uniformContainer unit_65_149);
clearWeaponCargoGlobal (uniformContainer unit_65_149);
(uniformContainer unit_65_149) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_65_149) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_65_149) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_65_149 addWeapon "tf_rf7800str";
unit_65_149 selectWeapon (primaryWeapon unit_65_149);
};

if (player == unit_66_150) exitwith {
removeallweapons unit_66_150;
removeallassigneditems unit_66_150;
removeHeadgear unit_66_150;
removeBackpack unit_66_150;
removeVest unit_66_150;

unit_66_150 addWeapon "ItemMap";
unit_66_150 addWeapon "ItemWatch";
unit_66_150 addWeapon "ItemCompass";
unit_66_150 addWeapon "ItemGPS";
unit_66_150 addWeapon "H_HelmetB_paint";
unit_66_150 addWeapon "NVGoggles_OPFOR";
unit_66_150 addWeapon "Rangefinder";
unit_66_150 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_150) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_150 addWeapon "arifle_MX_GL_F";
removeBackpack unit_66_150;
unit_66_150 addPrimaryWeaponItem "optic_Arco";
unit_66_150 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_66_150);
clearMagazineCargoGlobal (backpackContainer unit_66_150);
clearWeaponCargoGlobal (backpackContainer unit_66_150);
unit_66_150 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_150);
clearMagazineCargoGlobal (vestContainer unit_66_150);
clearWeaponCargoGlobal (vestContainer unit_66_150);
(vestContainer unit_66_150) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_150) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_150) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_150) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_150) addmagazinecargoGlobal ["UGL_FlareWhite_F",1];
(vestContainer unit_66_150) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_150);
clearMagazineCargoGlobal (uniformContainer unit_66_150);
clearWeaponCargoGlobal (uniformContainer unit_66_150);
(uniformContainer unit_66_150) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_150) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_150) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_150 addWeapon "tf_rf7800str";
unit_66_150 selectWeapon (primaryWeapon unit_66_150);
};

if (player == unit_66_151) exitwith {
removeallweapons unit_66_151;
removeallassigneditems unit_66_151;
removeHeadgear unit_66_151;
removeBackpack unit_66_151;
removeVest unit_66_151;

unit_66_151 addWeapon "ItemMap";
unit_66_151 addWeapon "ItemWatch";
unit_66_151 addWeapon "ItemCompass";
unit_66_151 addWeapon "ItemGPS";
unit_66_151 addWeapon "H_HelmetB_paint";
unit_66_151 addWeapon "NVGoggles_OPFOR";
unit_66_151 addWeapon "Binocular";
unit_66_151 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_151) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_151 addWeapon "arifle_MX_F";
removeBackpack unit_66_151;
unit_66_151 addPrimaryWeaponItem "optic_Arco";
unit_66_151 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_66_151);
clearMagazineCargoGlobal (backpackContainer unit_66_151);
clearWeaponCargoGlobal (backpackContainer unit_66_151);
(backpackContainer unit_66_151) additemcargoGlobal ["FirstAidKit",20];
unit_66_151 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_151);
clearMagazineCargoGlobal (vestContainer unit_66_151);
clearWeaponCargoGlobal (vestContainer unit_66_151);
(vestContainer unit_66_151) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_151) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_151) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_151) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_151) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_151);
clearMagazineCargoGlobal (uniformContainer unit_66_151);
clearWeaponCargoGlobal (uniformContainer unit_66_151);
(uniformContainer unit_66_151) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_151) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_151) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_151 addWeapon "tf_rf7800str";
unit_66_151 selectWeapon (primaryWeapon unit_66_151);
};

if (player == unit_66_152) exitwith {
removeallweapons unit_66_152;
removeallassigneditems unit_66_152;
removeHeadgear unit_66_152;
removeBackpack unit_66_152;
removeVest unit_66_152;

unit_66_152 addWeapon "ItemMap";
unit_66_152 addWeapon "ItemWatch";
unit_66_152 addWeapon "ItemCompass";
unit_66_152 addWeapon "ItemGPS";
unit_66_152 addWeapon "H_HelmetB";
unit_66_152 addWeapon "NVGoggles";
unit_66_152 addWeapon "Binocular";
unit_66_152 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",1];
unit_66_152 addWeapon "LMG_Mk200_F";
removeBackpack unit_66_152;
unit_66_152 addPrimaryWeaponItem "optic_ACO_grn";
unit_66_152 addVest "V_PlateCarrier2_rgr";
clearItemCargoGlobal (vestContainer unit_66_152);
clearMagazineCargoGlobal (vestContainer unit_66_152);
clearWeaponCargoGlobal (vestContainer unit_66_152);
(vestContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",2];
(vestContainer unit_66_152) addmagazinecargoGlobal ["SmokeShellGreen",5];
(vestContainer unit_66_152) addmagazinecargoGlobal ["HandGrenade",1];
(vestContainer unit_66_152) addmagazinecargoGlobal ["SmokeShellRed",2];
clearItemCargoGlobal (uniformContainer unit_66_152);
clearMagazineCargoGlobal (uniformContainer unit_66_152);
clearWeaponCargoGlobal (uniformContainer unit_66_152);
(uniformContainer unit_66_152) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
unit_66_152 addWeapon "tf_rf7800str";
unit_66_152 selectWeapon (primaryWeapon unit_66_152);
};

if (player == unit_66_153) exitwith {
removeallweapons unit_66_153;
removeallassigneditems unit_66_153;
removeHeadgear unit_66_153;
removeBackpack unit_66_153;
removeVest unit_66_153;

unit_66_153 addWeapon "ItemMap";
unit_66_153 addWeapon "ItemWatch";
unit_66_153 addWeapon "ItemCompass";
unit_66_153 addWeapon "ItemGPS";
unit_66_153 addWeapon "H_HelmetB_paint";
unit_66_153 addWeapon "NVGoggles_OPFOR";
unit_66_153 addWeapon "Binocular";
unit_66_153 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_66_153) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",1];
unit_66_153 addWeapon "arifle_MX_GL_F";
removeBackpack unit_66_153;
unit_66_153 addPrimaryWeaponItem "optic_Arco";
unit_66_153 addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer unit_66_153);
clearMagazineCargoGlobal (backpackContainer unit_66_153);
clearWeaponCargoGlobal (backpackContainer unit_66_153);
unit_66_153 addVest "V_PlateCarrierGL_rgr";
clearItemCargoGlobal (vestContainer unit_66_153);
clearMagazineCargoGlobal (vestContainer unit_66_153);
clearWeaponCargoGlobal (vestContainer unit_66_153);
(vestContainer unit_66_153) additemcargoGlobal ["FirstAidKit",1];
(vestContainer unit_66_153) addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",3];
(vestContainer unit_66_153) addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",3];
(vestContainer unit_66_153) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",6];
(vestContainer unit_66_153) addmagazinecargoGlobal ["3Rnd_HE_Grenade_shell",3];
clearItemCargoGlobal (uniformContainer unit_66_153);
clearMagazineCargoGlobal (uniformContainer unit_66_153);
clearWeaponCargoGlobal (uniformContainer unit_66_153);
(uniformContainer unit_66_153) addmagazinecargoGlobal ["SmokeShellGreen",5];
(uniformContainer unit_66_153) addmagazinecargoGlobal ["HandGrenade",1];
(uniformContainer unit_66_153) addmagazinecargoGlobal ["SmokeShellRed",2];
unit_66_153 addWeapon "tf_rf7800str";
unit_66_153 selectWeapon (primaryWeapon unit_66_153);
};

